---
title: "Ant Transition Matrix"
author: "Ali Campbell"
date: "9/19/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lme4)
library(nnet)
library(fixest)
library(mlogit)
library(dfidx)
library(effects)
library(bbmle)
```

```{r read_data}
#import the data
cactus <- read.csv("cholla_demography_20042019.csv", header = TRUE)
#str(cactus) ##<- problem: antcount is a factor
#levels(cactus$Antcount_t);levels(cactus$Antcount_t1)
## drop the offending rows -- this is a 2019 data entry problem
cactus <- cactus[-c(which(cactus$Antcount_t=="2-Jan"),which(cactus$Antcount_t1=="2-Jan")),]
cactus$antcount_t <- as.numeric(as.character(cactus$Antcount_t))
cactus$antcount_t1 <- as.numeric(as.character(cactus$Antcount_t1))
```

##Data Filtering
```{r volume}
## function for the volume of a cone

volume <- function(h, w, p){
  (1/3)*pi*h*(((w + p)/2)/2)^2
}
invlogit <- function(x){exp(x)/(1+exp(x))}

#Create volume columns
cactus$volume_t <- volume(cactus$Height_t,cactus$Width_t, cactus$Perp_t)
cactus$volume_t1 <- volume(cactus$Height_t1,cactus$Width_t1, cactus$Perp_t1)

#hist(log(cactus$volume_t))
```

```{r year_t_ants}
## assign ant counts of zero as vacant
cactus$Antsp_t[cactus$antcount_t==0] <- "vacant"
# here are the ordered levels of the current variable
Antsp_t_levels <- levels(cactus$Antsp_t)
# here is how I would like to collapse these into fewer bins -- most will be "other"
ant_t_levels <- rep("other",times=length(Antsp_t_levels))
## crem levels - elements 5,8,9
ant_t_levels[c(5,8,9)] <- "crem"
## liom levels - elements 15,18,19,20,21
ant_t_levels[c(15,18,19,20,21)] <- "liom"
## forelius levels - 12,13
ant_t_levels[c(12,13)] <- "for"
## vacant - 31
ant_t_levels[31] <- "vacant"
## create new variable merging levels as above
cactus$ant_t <- factor(cactus$Antsp_t,levels=Antsp_t_levels,labels=ant_t_levels)
summary(cactus$ant_t) ## there are too many "others". check these out.
filter(cactus,ant_t=="other")
## first, there are no ant data from 2007:
cactus$Antcount_t[cactus$Year_t==2007]
#so give these observations NA for ant status:
cactus$ant_t[cactus$Year_t==2007] <- NA
# also, if a plant was new in year t+1 it's year t ant status should be NA
cactus$ant_t[cactus$Newplant==1] <- NA
# plots 7 and 8 were added in 2011, so their year_t==2010 ant status should be NA
cactus$ant_t[cactus$Year_t==2010 & cactus$Plot==7] <- NA
cactus$ant_t[cactus$Year_t==2010 & cactus$Plot==8] <- NA
# check to see how many others this leaves -- still a lot
summary(cactus$ant_t)
## another 2019 data entry problem: new plants were not given Newplant==1 and their Survival is 0 (should be NA)
## for now here is my workaround: year t ==2018, height_t ==NA, height_t1 !=NA
cactus$ant_t[cactus$Year_t==2018 & is.na(cactus$Height_t) & !is.na(cactus$Height_t1)] <- NA
## finally there are these plants with Antsp_t=="" for all kinds of reasons but bottom line is that we don't have ant status
cactus$ant_t[cactus$Antsp_t==""]<-NA
## inspect the "others" visually
cactus %>% filter(ant_t=="other") %>% select(Antsp_t,ant_t)
## I am satisfied that everything assigned other is correctly assigned

```

```{r ant_time_series}
## plot a time series of ant frequency by year
ant_freq_ts <- cactus %>% 
  select(Year_t,ant_t) %>% 
  drop_na() %>% 
  group_by(Year_t,ant_t) %>% 
  summarise(n = n()) %>% 
  mutate(freq = n / sum(n))

plot(ant_freq_ts$Year_t[ant_freq_ts$ant_t=="vacant"],ant_freq_ts$freq[ant_freq_ts$ant_t=="vacant"],type="b",ylim=c(0,1),pch=16,cex=1.5,
     xlab="Year",ylab="Frequency")
legend("topleft",legend=c("Vacant","Liom.","Crem.","For.","Other"),pch=16,col=c("black","blue","red","green","pink"))
points(ant_freq_ts$Year_t[ant_freq_ts$ant_t=="liom"],ant_freq_ts$freq[ant_freq_ts$ant_t=="liom"],type="b",pch=16,cex=1.5,col="blue")
points(ant_freq_ts$Year_t[ant_freq_ts$ant_t=="crem"],ant_freq_ts$freq[ant_freq_ts$ant_t=="crem"],type="b",pch=16,cex=1.5,col="red")
points(ant_freq_ts$Year_t[ant_freq_ts$ant_t=="for"],ant_freq_ts$freq[ant_freq_ts$ant_t=="for"],type="b",pch=16,cex=1.5,col="green")
points(ant_freq_ts$Year_t[ant_freq_ts$ant_t=="other"],ant_freq_ts$freq[ant_freq_ts$ant_t=="other"],type="b",pch=16,cex=1.5,col="pink")

```


```{r year_t1_ants}
## assign ant counts of zero as vacant
cactus$Antsp_t1[cactus$antcount_t1==0] <- "vacant"
## repeat for t1 -- these indices are different
Antsp_t1_levels <- levels(cactus$Antsp_t1)
# here is how I would like to collapse these into fewer bins -- most will be "other"
ant_t1_levels <- rep("other",times=length(Antsp_t1_levels))
## crem levels 
ant_t1_levels[c(8,9,10)] <- "crem"
## liom levels 
ant_t1_levels[c(19,20,21,22)] <- "liom"
## forelius levels 
ant_t1_levels[c(13,14,15)] <- "for"
## vacant 
ant_t1_levels[32] <- "vacant"
## create new variable merging levels as above
cactus$ant_t1 <- factor(cactus$Antsp_t1,levels=Antsp_t1_levels,labels=ant_t1_levels)
summary(cactus$ant_t1) ## there are too many "others" -- same deal as above
## first, there are no ant data from 2007 so give these observations NA for ant status:
cactus$ant_t1[cactus$Year_t1==2007] <- NA
## if we did not get size in t1 assume we did not get ant
cactus$ant_t1[is.na(cactus$Height_t1)] <- NA
# check to see how many others this leaves -- still a lot
summary(cactus$ant_t1)
## there are some Antsp_t1=="" that show up as "other"
cactus %>% filter(Antsp_t1=="" & ant_t1=="other")
## not sure why this happens but apparently there are some plants for which we have ant counts but no ant sp. Could be a mix in comments. For now make these NA.
cactus$ant_t1[cactus$Antsp_t1==""] <- NA
## inspect the "others" visually
cactus %>% filter(ant_t1=="other") %>% select(Antsp_t1,ant_t1)
## I am satisfied that everything assigned other in t1 is correctly assigned

```

## Vital rates

```{r survival}
surv_model <- glm(Survival_t1 ~ log(volume_t),family="binomial",data=cactus)
surv_model_ant <- glm(Survival_t1 ~ log(volume_t) + ant_t,family="binomial",data=cactus)
surv_model_ant_interact <- glm(Survival_t1 ~ log(volume_t) * ant_t,family="binomial",data=cactus)
AICtab(surv_model,surv_model_ant,surv_model_ant_interact)

ggplot(cactus, aes(y=Survival_t1, x=log(volume_t), col=ant_t)) +  geom_point(alpha = 0.1) +
  geom_smooth(data=cactus, method = "glm", formula='y~x', method.args = list(family = "binomial"), se = FALSE) 

```

```{r growth}
grow_model <- lm(log(volume_t1) ~ log(volume_t),data=cactus)
grow_model_ant <- lm(log(volume_t1) ~ log(volume_t) + ant_t,data=cactus)
grow_model_ant_interact <- lm(log(volume_t1) ~ log(volume_t) * ant_t,data=cactus)
AICtab(grow_model,grow_model_ant,grow_model_ant_interact)

plot(log(cactus$volume_t),log(cactus$volume_t1),type="n")
points(log(cactus$volume_t[cactus$ant_t=="vacant"]),log(cactus$volume_t1[cactus$ant_t=="vacant"]),col=alpha("black",0.1))
abline(coef(grow_model_ant_interact)[1]+coef(grow_model_ant_interact)[6],coef(grow_model_ant_interact)[2]+coef(grow_model_ant_interact)[10],col="black")
points(log(cactus$volume_t[cactus$ant_t=="liom"]),log(cactus$volume_t1[cactus$ant_t=="liom"]),col=alpha("blue",0.1))
abline(coef(grow_model_ant_interact)[1]+coef(grow_model_ant_interact)[5],coef(grow_model_ant_interact)[2]+coef(grow_model_ant_interact)[9],col="blue")
points(log(cactus$volume_t[cactus$ant_t=="crem"]),log(cactus$volume_t1[cactus$ant_t=="crem"]),col=alpha("red",0.1))
abline(coef(grow_model_ant_interact)[1]+coef(grow_model_ant_interact)[3],coef(grow_model_ant_interact)[2]+coef(grow_model_ant_interact)[7],col="red")
points(log(cactus$volume_t[cactus$ant_t=="for"]),log(cactus$volume_t1[cactus$ant_t=="for"]),col=alpha("green",0.1))
abline(coef(grow_model_ant_interact)[1]+coef(grow_model_ant_interact)[4],coef(grow_model_ant_interact)[2]+coef(grow_model_ant_interact)[8],col="green")
points(log(cactus$volume_t[cactus$ant_t=="other"]),log(cactus$volume_t1[cactus$ant_t=="other"]),col=alpha("pink",0.1))
abline(coef(grow_model_ant_interact)[1],coef(grow_model_ant_interact)[2],col="pink")

```


```{r floral_abortion}
## see what we have in terms of counts of total, good, and aborted flowerbuds
cactus %>% 
  group_by(Year_t) %>% 
  select(Goodbuds_t,TotFlowerbuds_t,ABFlowerbuds_t) %>% 
  summarise(mean1 = mean(Goodbuds_t,na.rm=T),
            mean2 = mean(TotFlowerbuds_t,na.rm=T),
            mean3 = mean(ABFlowerbuds_t,na.rm=T))
## only goodbuds in 2009-2012 so no abortion data
## before that we have all three counts
## 2013 and later, just counts of goodbuds and aborted

abort_model <- glm(cbind(Goodbuds_t,ABFlowerbuds_t) ~ 1,family="binomial",data=cactus)
abort_model_ant <- glm(cbind(Goodbuds_t,ABFlowerbuds_t) ~ ant_t,family="binomial",data=cactus)
AICtab(abort_model,abort_model_ant)

## view the raw proportions
cactus %>% 
  mutate(viab_rate = Goodbuds_t/(Goodbuds_t+ABFlowerbuds_t)) %>% 
  group_by(ant_t) %>% 
  summarise(mean_viab = mean(viab_rate,na.rm=T),
            n_viab = n())

```


##Ant Transition Matrix

```{r ant_matrix}
table(cactus$ant_t, cactus$ant_t1)
plot(table(cactus$ant_t, cactus$ant_t1))

transition_mat <- prop.table(table(cactus$ant_t, cactus$ant_t1),margin=2)
## check that columns sum to 1
colSums(transition_mat)
```

```{r multinom}
## for multinomial model, first relevel the ant factor to have a reference level, which will be vacant
cactus$ant_t1_relevel <- relevel(cactus$ant_t1,ref = "vacant")
## create new variable for plant reproductive state transition (we know nectar goes up when plants start flowering)
cactus$repro_trans <- c()
cactus$repro_trans[cactus$Goodbuds_t==0 & cactus$Goodbuds_t1==0]<-"VV"
cactus$repro_trans[cactus$Goodbuds_t==0 & cactus$Goodbuds_t1>0]<-"VF"
cactus$repro_trans[cactus$Goodbuds_t>0 & cactus$Goodbuds_t1==0]<-"FV"
cactus$repro_trans[cactus$Goodbuds_t>0 & cactus$Goodbuds_t1>0]<-"FF"

## here is a base model, no predictor variables
ant_transition_models<-list()
## null model
ant_transition_models[[1]] <- multinom(ant_t1_relevel ~ 1, data = cactus)
## previous state dependence
ant_transition_models[[2]] <- multinom(ant_t1_relevel ~ 0+ant_t, data = cactus)
## previous state and size
ant_transition_models[[3]] <- multinom(ant_t1_relevel ~ 0+ant_t + log(volume_t), data = cactus)
ant_transition_models[[4]] <- multinom(ant_t1_relevel ~ 0+ant_t * log(volume_t), data = cactus)
## previous state and reproductive transition
ant_transition_models[[5]] <- multinom(ant_t1_relevel ~ 0+ant_t + as.factor(repro_trans), data = cactus)
ant_transition_models[[6]] <- multinom(ant_t1_relevel ~ 0+ant_t * as.factor(repro_trans), data = cactus)
## all three
ant_transition_models[[7]] <- multinom(ant_t1_relevel ~ 0+ant_t + log(volume_t) + as.factor(repro_trans), data = cactus)
ant_transition_models[[8]] <- multinom(ant_t1_relevel ~ 0+ant_t * as.factor(repro_trans) + log(volume_t), data = cactus) 
ant_transition_models[[9]] <- multinom(ant_t1_relevel ~ 0+ant_t * log(volume_t) + as.factor(repro_trans), data = cactus) 
ant_transition_models[[10]] <- multinom(ant_t1_relevel ~ 0+ant_t + log(volume_t) * as.factor(repro_trans), data = cactus) 
##3-way intx does not converge

AICtab(ant_transition_models)
```
```{r visualize multinomial}
summary(ant_transition_models[[5]])

```

```{r ant_size_distributions}
<<<<<<< HEAD
plot(density(log(cactus$volume_t[cactus$ant_t=="vacant"]),na.rm=T),type="l",lwd=3,ylim=c(0,0.3),main=" ",
     xlab="Plant size (log volume)")
lines(density(log(cactus$volume_t[cactus$ant_t=="liom"]),na.rm=T),type="l",lwd=3,col="blue")
lines(density(log(cactus$volume_t[cactus$ant_t=="crem"]),na.rm=T),type="l",lwd=3,col="red")
lines(density(log(cactus$volume_t[cactus$ant_t=="for"]),na.rm=T),type="l",lwd=3,col="green")
lines(density(log(cactus$volume_t[cactus$ant_t=="other"]),na.rm=T),type="l",lwd=3,col="pink")
legend("topleft",legend=c("Vacant","Liom.","Crem.","For.","Other"),pch=16,col=c("black","blue","red","green","pink"),bty="n",lwd=3)


```

```{r}

=======
plot(density(log(cactus$volume_t[cactus$ant_t=="vacant"]),na.rm=T),type="l",lwd=2,ylim=c(0,0.3))
lines(density(log(cactus$volume_t[cactus$ant_t=="liom"]),na.rm=T),type="l",lwd=2,col="blue")
lines(density(log(cactus$volume_t[cactus$ant_t=="crem"]),na.rm=T),type="l",lwd=2,col="red")
lines(density(log(cactus$volume_t[cactus$ant_t=="for"]),na.rm=T),type="l",lwd=2,col="green")
lines(density(log(cactus$volume_t[cactus$ant_t=="other"]),na.rm=T),type="l",lwd=2,col="pink")


>>>>>>> c1e0999cfa5455c5c95bf2c411719e4cb577f2ba
par(mfrow=c(2,3))
plot(density(log(cactus$volume_t[cactus$ant_t=="vacant"]),na.rm=T))
points(log(cactus$volume_t[cactus$ant_t=="vacant"]),
       rep(0,times=length(log(cactus$volume_t[cactus$ant_t=="vacant"]))),pch="|")
plot(density(log(cactus$volume_t[cactus$ant_t=="liom"]),na.rm=T))
points(log(cactus$volume_t[cactus$ant_t=="liom"]),
       rep(0,times=length(log(cactus$volume_t[cactus$ant_t=="liom"]))),pch="|")
plot(density(log(cactus$volume_t[cactus$ant_t=="crem"]),na.rm=T))
points(log(cactus$volume_t[cactus$ant_t=="crem"]),
       rep(0,times=length(log(cactus$volume_t[cactus$ant_t=="crem"]))),pch="|")
plot(density(log(cactus$volume_t[cactus$ant_t=="for"]),na.rm=T))
points(log(cactus$volume_t[cactus$ant_t=="for"]),
       rep(0,times=length(log(cactus$volume_t[cactus$ant_t=="for"]))),pch="|")
plot(density(log(cactus$volume_t[cactus$ant_t=="other"]),na.rm=T))
points(log(cactus$volume_t[cactus$ant_t=="other"]),
       rep(0,times=length(log(cactus$volume_t[cactus$ant_t=="other"]))),pch="|")
```

