---
title: "Multinomial Models"
author: "Ali Campbell"
date: "2/8/2021"
output: html_document
---

```{r setup, include=FALSE}
library(rstanarm)
library(brms)  # for models
library(tidyverse)
library(rstan)
library(StanHeaders)
library(shinystan)
library(bayesplot)
library(devtools)
library(tidyr)
library(lattice)
library(lme4)
library(dplyr)
library(tidyverse)
library(nnet)
library(fixest)
library(mlogit)
library(dfidx)
library(effects)
library(bbmle)
library(magrittr)
library(Gmisc)
library(RColorBrewer)
library(ggeffects)
library(heplots)
library("posterior")
#library(sjPlot)
knitr::opts_chunk$set(echo = TRUE)
options(mc.cores = parallel::detectCores())
setwd("/Users/alicampbell/Box Sync/Grad/Cactus/Shared Code/ant_cactus_demography/Stan")
```

#### Data

```{r}
data <- cactus[ ,c("Plot","Year_t","Survival_t1","ant_t","ant_t1","volume_t","volume_t1")]
data <- na.omit(data)
data$ant <- as.integer(data$ant_t)
## add columns for each ant classification so they can be binary
data$crem <- 0 ##2
data$liom <- 0 ##3
data$other <- 0 ##1
data$vacant <- 0 ##4
for(i in 1:nrow(data)){
  if(data$ant[i] == 1){data$other[i] <- 1}
  if(data$ant[i] == 2){data$crem[i] <- 1}
  if(data$ant[i] == 3){data$liom[i] <- 1}
  if(data$ant[i] == 4){data$vacant[i] <- 1}
}
```


