---
title: "Simulate Data"
author: "Ali Campbell"
date: "2/17/2021"
output: html_document
---


```{r setup, include=FALSE}
library(rstanarm)
#library(rstansim)
library(brms)  # for models
library(tidyverse)
library(rstan)
library(StanHeaders)
library(shinystan)
#library(bayesplot)
library(devtools)
library(tidyr)
library(lattice)
library(lme4)
library(dplyr)
library(tidyverse)
library(nnet)
library(fixest)
library(mlogit)
library(dfidx)
library(effects)
library(bbmle)
library(magrittr)
library(Gmisc)
library(RColorBrewer)
library(ggeffects)
library(heplots)
library("posterior")
#library(sjPlot)
knitr::opts_chunk$set(echo = TRUE)
options(mc.cores = parallel::detectCores())
setwd("/Users/alicampbell/Box Sync/Grad/Cactus/Shared Code/ant_cactus_demography/Stan")
```

#### Data

```{r}
cactus$ant_t1_relevel <- relevel(cactus$ant_t1,ref = "vacant")
data <- cactus[ ,c("Plot","Year_t","Survival_t1","ant_t","ant_t1","volume_t","volume_t1","repro_state_t1", "ant_t1_relevel")]
data <- na.omit(data)
data$ant <- as.integer(data$ant_t)
data$ant1 <- as.integer(data$ant_t1_relevel)
## add columns for each ant classification so they can be binary
data$crem <- 0 ##2
data$liom <- 0 ##3
data$other <- 0 ##1
data$vacant <- 0 ##4
for(i in 1:nrow(data)){
  if(data$ant[i] == 1){data$other[i] <- 1}
  if(data$ant[i] == 2){data$crem[i] <- 1}
  if(data$ant[i] == 3){data$liom[i] <- 1}
  if(data$ant[i] == 4){data$vacant[i] <- 1}
}
data$Year_t <- as.factor(data$Year_t)
data$year <- as.integer(data$Year_t)
data$Plot <- as.factor(data$Plot)
data$plot <- as.integer(data$Plot)


## Flower Data Set
flower <- cactus[ , c("TotFlowerbuds_t","ABFlowerbuds_t","Goodbuds_t","ant_t", "repro_state_t1","volume_t","volume_t1","Year_t","Plot")]
flower <- na.omit(flower)
flower$ant <- as.integer(flower$ant_t)
flower$Year_t <- as.factor(flower$Year_t)
flower$year <- as.integer(flower$Year_t)
flower$Plot <- as.factor(flower$Plot)
flower$plot <- as.integer(flower$Plot)
```

## Simulate for Base Models (no ants)
#### Growth
```{r Growth Model}
vol <- data$volume_t
y <- data$volume_t1
N <- as.integer(nrow(data))
## Rerun linear model with that new data
#mod1 <- lm(y~x, data = data)
#summary(grow_model)
#summary(mod1)
## Now we can extract some important statistics
lm_alpha <- summary(grow_model)$coeff[1]  # the intercept
lm_beta <- summary(grow_model)$coeff[2]  # the slope
lm_sigma <- sigma(grow_model)  # the residual error
## Make it a dataframe
stan_data <- list(N = N, vol = vol, y = y)
## Write the model in stan
#note that we are using flat priors here which are non restrictive
write("// Stan model for simple growth regression
data {
 int < lower = 1 > N; // Sample size
 vector[N] vol; // Predictor
 vector[N] y; // Outcome
}
transformed data {
  real<lower = 0> mean_y = mean(to_vector(y));
  real<lower = 0> sd_y = sd(to_vector(y));
}
parameters {
 real alpha; // Intercept
 real beta; // Slope (regression coefficients)
 real < lower = 0 > sigma; // Error SD
}
model {
// Priors
alpha ~ normal(0,100);
beta ~ normal(0,100); 
//sigma ~ exponential(0,0);
 y ~ normal(alpha + vol * beta , sigma); // The Model
}
generated quantities {
  real  y_rep[N] = normal_rng(alpha + beta * vol, sigma);
  real  mean_y_rep = mean(to_vector(y_rep));
  real  sd_y_rep = sd(to_vector(y_rep));
} // The posterior predictive distribution",
"grow_lm1.stan")
stanc("grow_lm1.stan")
## Save the file path
stanny <- "grow_lm1.stan"
## Now we fit the model
fit_grow <- stan(file = stanny, data = stan_data, warmup = 500, iter = 1000, chains = 1, cores = 2, thin = 1)
fit_grow
#class(fit)
posterior_grow <- as.data.frame(fit_grow)
print(colnames(posterior_grow))
mat_grow <- as.matrix(fit_grow)

par(mfrow = c(1,1))
plot(density(posterior_grow$mean_y_rep), xlim = c(55000, 67000))
abline(v = mean(na.omit(cactus$volume_t1)), col = "red", lty = 2)

```

#### Survival
```{r Survival Model}
vol = data$volume_t
y <- data$Survival_t1
N <- nrow(data)
#import things from the r regression models for comparison
lm_alpha <- summary(surv_model)$coeff[1]  # the intercept
lm_beta <- summary(surv_model)$coeff[2]  # the slope
summary(surv_model)
## Make it a dataframe
stan_data <- list(N = N, vol = vol, y = y)
## Write the model in stan
#note that we are using flat priors here which are non restrictive
write("// Stan model for simple survival regression

data {
  int <lower=0> N;
  vector[N] vol;
  int <lower=0,upper=1> y[N];
}
transformed data {
  real<lower = 0> mean_y = mean(to_vector(y));
  real<lower = 0> sd_y = sd(to_vector(y));
}
parameters {
  real alpha;
  real beta;
}
model {
 // Priors
 alpha ~ normal(0,100);
 beta ~ normal(0,100); 
 // Model
 y ~ bernoulli_logit(alpha + beta * vol);
}
generated quantities {
  int<lower = 0> y_rep[N] = bernoulli_logit_rng(alpha + beta * vol);
  real<lower = 0> mean_y_rep = mean(to_vector(y_rep));
  real<lower = 0> sd_y_rep = sd(to_vector(y_rep));
} 
",

"surv_lm1.stan")
## Check that you wrote a file
stanc("surv_lm1.stan")
## Save the file path
stanny <- "surv_lm1.stan"
## Now we fit the model
fit_surv <- stan(file = stanny, data = stan_data, warmup = 500, iter = 1000, chains = 1, cores = 2, thin = 1)
fit_surv

posterior_surv <- as.data.frame(fit_surv)
print(colnames(posterior_surv))

par(mfrow = c(1,1))
plot(density(posterior_surv$mean_y_rep), xlim = c(0.934,1.0002))
abline(v = mean(na.omit(cactus$Survival_t1)), col = "red", lty = 2)
```

#### Total Flowers
```{r Total Flowers Model}
y <- flower$TotFlowerbuds_t
N <- nrow(flower)
stan_data <- list(N = N, ## number of observations
                  y = y ## response survival next year
) 

write("// Stan model for simple total flowers regression

data {
 int < lower = 1 > N; // Sample size
 int y[N]; // Outcome
}
transformed data {
  real<lower = 0> mean_y = mean(to_vector(y));
  real<lower = 0> sd_y = sd(to_vector(y));
}
parameters {
  real<lower = 0> lambda; //intercept, unique to ant
}
model {
// Priors
 lambda ~ exponential(0.2);
 // Model
 y ~ poisson(lambda);
}
generated quantities {
  int<lower = 0> y_rep[N] = poisson_rng(rep_array(lambda, N));
  real<lower = 0> mean_y_rep = mean(to_vector(y_rep));
  real<lower = 0> sd_y_rep = sd(to_vector(y_rep));
} 
// The posterior predictive distribution",

"flower_lm1.stan")
## Check that you wrote a file
stanc("flower_lm1.stan")
## Save the file path
stanny <- "flower_lm1.stan"
## Now we fit the model
fit_flow <- stan(file = stanny, data = stan_data, warmup = 50, iter = 100, chains = 1, cores = 2, thin = 1)
fit_flow

posterior_flow <- as.data.frame(fit_flow)
print(colnames(posterior_flow))
lm_lambda <- summary(flower_model)$coeff[2]

plot(density(posterior_flow$mean_y_rep), xlim = c(4,12))
abline(v = mean(na.omit(cactus$TotFlowerbuds_t1)), col = "red", lty = 2)

```

#### Reproduction
```{r Reproductive Model}
vol1 <- flower$volume_t1
y = flower$repro_state_t1
N = nrow(flower)
stan_data <- list(N = N, ## number of observations
                  y = y, ## response survival next year
                  vol1 = vol1
) 

write("// Stan model for simple total flowers regression

data {
 int < lower = 1 > N; // Sample size
 int <lower = 0, upper = 1> y[N]; // Outcome
 vector[N] vol1;	//size_t
}
transformed data {
  real<lower = 0> mean_y = mean(to_vector(y));
  real<lower = 0> sd_y = sd(to_vector(y));
}
parameters {
  real beta0; //intercept, unique to ant sp
  real beta1; //slope, unique to ant sp
  real<lower = 0> sigma;
}
model {
 // Priors
 beta0 ~ normal(0,100);
 beta1 ~ normal(0,100); 
 // Model
 y ~ bernoulli_logit(beta0 + beta1 * vol1);
}
generated quantities {
  int<lower = 0> y_rep[N] = bernoulli_logit_rng(beta0 + beta1 * vol1);
  real<lower = 0> mean_y_rep = mean(to_vector(y_rep));
  real<lower = 0> sd_y_rep = sd(to_vector(y_rep));
} 
",

"repro_lm1.stan")

## Check that you wrote a file
stanc("repro_lm1.stan")
## Save the file path
stanny <- "repro_lm1.stan"
## Now we fit the model
fit_repro <- stan(file = stanny, data = stan_data, warmup = 50, iter = 100, chains = 1, cores = 2, thin = 1)
fit_repro

posterior_repro <- as.data.frame(fit_repro)
print(colnames(posterior_repro))

par(mfrow = c(1,1))
plot(density(posterior_repro$mean_y_rep))
abline(v = mean(na.omit(cactus$repro_state_t1)), col = "red", lty = 2)
```

## Simulate for Base Models (ants)
#### Growth
```{r Growth Ant Model}
vol = data$volume_t
y = data$volume_t1
N = nrow(data)
N_ant = 4
ant = data$ant
stan_data <- list(N = N, ## number of observations
                  vol = vol, ## predictors volume
                  y = y, ## response volume next year
                  ant = ant,## predictors ants
                  N_ant = N_ant
) 
## Write the model in stan
#note that we are using flat priors here which are non restrictive
write("// Stan model for simple growth regression

data {
  int <lower = 1> N; // number of observations
  int <lower = 1> N_ant; // number of ant states
  int <lower = 1, upper = N_ant> ant[N]; // the list of ant species 
  vector[N] vol;	//size_t
  vector[N] y; // size_t1
}
transformed data {
  real<lower = 0> mean_y = mean(to_vector(y));
  real<lower = 0> sd_y = sd(to_vector(y));
}
parameters {
  vector[N_ant] beta0; //intercept, unique to ant sp
  vector[N_ant] beta1; //slope, unique to ant sp
  real<lower = 0> sigma;
}

transformed parameters{
  vector[N] mu; //linear predictor for the mean
  for(i in 1:N){
    mu[i] = beta0[ant[i]] + beta1[ant[i]] * vol[i];
  }
}

model {
  y ~ normal(mu, sigma); // likelihood
}
generated quantities{
  real  y_rep[N] = normal_rng(mu, sigma);
  real  mean_y_rep = mean(to_vector(y_rep));
  real  sd_y_rep = sd(to_vector(y_rep));
}
",

"grow_ant_lm1.stan")
## Check that you wrote a file
stanc("grow_ant_lm1.stan")
## Save the file path
stanny <- "grow_ant_lm1.stan"
## Now we fit the model
fit_grow_ant <- stan(file = stanny, data = stan_data, warmup = 5, iter = 10, chains = 1, cores = 2, thin = 1)
fit_grow_ant
#class(fit)
posterior_grow_ant <- as.data.frame(fit_grow_ant)
print(colnames(posterior_grow_ant))

par(mfrow = c(1,1))
plot(density(posterior_grow_ant$mean_y_rep), xlim = c(53375, 66738))
abline(v = mean(na.omit(cactus$volume_t1)), col = "red", lty = 2)
```

#### Survival
```{r Survival Model Ant}
vol = data$volume_t
y = data$Survival_t1
N = nrow(data)
N_ant = 4
ant = data$ant
stan_data <- list(N = N, ## number of observations
                  vol = vol, ## predictors volume
                  y = y, ## response survival next year
                  ant = ant,## predictors ants
                  N_ant = N_ant
) 

write("// Stan model for simple ant survival regression
data {
  int <lower = 1> N; // number of observations
  int <lower = 1> N_ant; // number of ant states
  int <lower = 1, upper = N_ant> ant[N]; // the list of ant species 
  vector[N] vol;	//size_t
  int <lower = 0, upper = 1> y[N]; // survival in year t1
}
transformed data {
  real<lower = 0> mean_y = mean(to_vector(y));
  real<lower = 0> sd_y = sd(to_vector(y));
}
parameters {
  vector[N_ant] beta0; //intercept, unique to ant sp
  vector[N_ant] beta1; //slope, unique to ant sp
  real<lower = 0> sigma;
}
transformed parameters{
  vector[N] mu; //linear predictor for the mean
  for(i in 1:N){
    mu[i] = beta0[ant[i]] + beta1[ant[i]] * vol[i];
  }
}
model {
//Priors
 beta0 ~ normal(0,100);
 beta1 ~ normal(0,100);
 //Model
 y ~ bernoulli_logit(mu);
}
generated quantities {
  int<lower = 0> y_rep[N] = bernoulli_logit_rng(mu);
  real<lower = 0> mean_y_rep = mean(to_vector(y_rep));
  real<lower = 0> sd_y_rep = sd(to_vector(y_rep));
}
",

"surv_ant_lm1.stan")
## Check that you wrote a file
stanc("surv_ant_lm1.stan")
## Save the file path
stanny <- "surv_ant_lm1.stan"
## Now we fit the model
fit_surv_ant <- stan(file = stanny, data = stan_data, warmup = 5, iter = 10, chains = 1, cores = 2, thin = 1)
fit_surv_ant

#class(fit)
posterior_surv_ant <- as.data.frame(fit_surv_ant)
print(colnames(posterior_surv_ant))

par(mfrow = c(1,1))
plot(density(posterior_surv_ant$mean_y_rep), xlim = c(0.879,0.94))
abline(v = mean(na.omit(cactus$Survival_t1)), col = "red", lty = 2)
```

#### Total Flowers
```{r}
y <- flower$TotFlowerbuds_t
vol = flower$volume_t
N = nrow(flower)
N_ant = 4
ant = flower$ant
stan_data <- list(N = N, ## number of observations
                  y = y, ## response survival next year
                  vol = vol,
                  N_ant = N_ant,
                  ant = ant
) 

write("// Stan model for simple total flowers regression
data {
 int <lower = 1> N; // number of observations
  int <lower = 1> N_ant; // number of ant states
  int <lower = 1, upper = N_ant> ant[N]; // the list of ant species 
  vector[N] vol;	//size_t
  int <lower = 0> y[N]; // survival in year t1
}
transformed data {
  real<lower = 0> mean_y = mean(to_vector(y));
  real<lower = 0> sd_y = sd(to_vector(y));
}
parameters {
  vector[N_ant] beta0; //intercept, unique to ant sp
  vector[N_ant] beta1; //slope, unique to ant sp
  real<lower = 0> sigma;
}
transformed parameters{
  vector[N] mu; //linear predictor for the mean
  for(i in 1:N){
    mu[i] = beta0[ant[i]] + beta1[ant[i]] * vol[i];
  }
}
model {
 // Model
 y ~ poisson(mu);
}
generated quantities {
  int<lower = 0> y_rep[N] = poisson_rng(mu);
  real<lower = 0> mean_y_rep = mean(to_vector(y_rep));
  real<lower = 0> sd_y_rep = sd(to_vector(y_rep));
} 
",

"flower_ant_lm1.stan")
## Check that you wrote a file
stanc("flower_ant_lm1.stan")
## Save the file path
stanny <- "flower_ant_lm1.stan"
## Now we fit the model
fit_flow_ant <- stan(file = stanny, data = stan_data, warmup = 5, iter = 10, chains = 1, cores = 2, thin = 1)
fit_flow_ant

posterior_flow_ant <- as.data.frame(fit_flow_ant)
print(colnames(posterior_flow_ant))

par(mfrow = c(1,1))
plot(density(posterior_flow_ant$mean_y_rep), xlim = c(0, 133450))
abline(v = mean(y), col = "red", lty = 2)
```

#### Reproduction
```{r}
vol1 <- flower$volume_t1
y = flower$repro_state_t1
N = nrow(flower)
N_ant = 4
ant = flower$ant
stan_data <- list(N = N, ## number of observations
                  y = y, ## response survival next year
                  vol1 = vol1,
                  N_ant = N_ant,
                  ant = ant
)

write("// Stan model for simple total flowers regression

data {
  int <lower = 1> N; // number of observations
  int <lower = 1> N_ant; // number of ant states
  int <lower = 1, upper = N_ant> ant[N]; // the list of ant species 
  vector[N] vol1;	//size_t
  int <lower = 0, upper = 1> y[N]; // survival in year t1
}
transformed data {
  real<lower = 0> mean_y = mean(to_vector(y));
  real<lower = 0> sd_y = sd(to_vector(y));
}
parameters {
  vector[N_ant] beta0; //intercept, unique to ant sp
  vector[N_ant] beta1; //slope, unique to ant sp
  real<lower = 0> sigma;
}
transformed parameters{
  vector[N] mu; //linear predictor for the mean
  for(i in 1:N){
    mu[i] = beta0[ant[i]] + beta1[ant[i]] * vol1[i];
  }
}
model {
 // Priors
 beta0 ~ normal(0,100);
 beta1 ~ normal(0,100); 
 // Model
 y ~ bernoulli_logit(mu);
}
generated quantities {
  int<lower = 0> y_rep[N] = bernoulli_logit_rng(mu);
  real<lower = 0> mean_y_rep = mean(to_vector(y_rep));
  real<lower = 0> sd_y_rep = sd(to_vector(y_rep));
} 
",

"repro_ant_lm1.stan")

## Check that you wrote a file
stanc("repro_ant_lm1.stan")
## Save the file path
stanny <- "repro_ant_lm1.stan"
## Now we fit the model
fit_repro_ant <- stan(file = stanny, data = stan_data, warmup = 5, iter = 10, chains = 1, cores = 2, thin = 1)
fit_repro_ant

posterior_repro_ant <- as.data.frame(fit_repro_ant)
print(colnames(posterior_repro_ant))

par(mfrow = c(1,1))
plot(density(posterior_repro_ant$mean_y_rep))
abline(v = mean(y), col = "red", lty = 2)
```

## Simulate for Mixed Models 
#### Growth
```{r Growth Mixed Ant Model}
vol = log(data$volume_t)
y = log(data$volume_t1)
N = nrow(data)
N_ant = 4
ant = data$ant
N_Year <- max(data$year)
N_Plot <- max(data$plot)
plot <- data$plot
year <- data$year
stan_data <- list(N = N, ## number of observations
                  vol = vol, ## predictors volume
                  y = y, ## response volume next year
                  ant = ant,## predictors ants
                  N_ant = N_ant, ## number of ant states
                  N_Year = N_Year, ## number of years
                  N_Plot = N_Plot, ## number of plots
                  plot = plot, ## predictor plots
                  year = year ## predictor years
) 
## Write the model in stan
#note that we are using flat priors here which are non restrictive
write("// Stan model for simple growth regression
data {
  int <lower = 1> N; // number of observations
  int <lower = 1> N_ant; // number of ant states
  int <lower = 1, upper = N_ant> ant[N]; // the list of ant species 
  vector[N] vol;	//size_t
  vector[N] y; // size_t1
  int<lower=1> N_Year; //number of plots
  int<lower=1> N_Plot; //number of years
  int<lower=1, upper=N_Plot> plot[N]; // plot
  int<lower=1, upper=N_Year> year[N]; // year
}
transformed data {
  real<lower = 0> mean_y = mean(to_vector(y));
  real<lower = 0> sd_y = sd(to_vector(y));
}
parameters {
  vector[N_ant] beta0; //intercept, unique to ant sp
  vector[N_ant] beta1; //slope, unique to ant sp
  vector[N_Plot] u; //subject intercepts
  vector[N_Year] w; //item intercepts
  real < lower = 0 > sigma; // Error SD
  real < lower = 0 > sigma_u; // plot SD
  real < lower = 0 > sigma_w; // year SD
}
transformed parameters{
  vector[N] mu; //linear predictor for the mean
  for(i in 1:N){
    mu[i] = beta0[ant[i]] + beta1[ant[i]] * vol[i] + u[plot[i]] + w[year[i]];
  }
}
model {
  u ~ normal(0, sigma_u); // plot random effects
  w ~ normal(0, sigma_w); // year random effects
  beta0 ~ normal(0,100); // intercept distribution
  beta1 ~ normal(0,100); // slope distribution
  for(i in 1:N){
    y[i] ~ normal(mu[i], sigma);
  }
}
generated quantities{
  real  y_rep[N] = normal_rng(mu, sigma);
  real  mean_y_rep = mean(to_vector(y_rep));
  real  sd_y_rep = sd(to_vector(y_rep));
}
",
"grow_ant_mix_lm1.stan")
## Check that you wrote a file
#stanc("grow_ant_mix_lm1.stan")
## Save the file path
stanny <- "grow_ant_mix_lm1.stan"
## Now we fit the model
fit_grow_mix_ant <- stan(file = stanny, data = stan_data, warmup = 500, iter = 1000, chains = 1, cores = 2, thin = 1)
#fit_grow_mix_ant
#class(fit)
posterior_grow_mix_ant <- as.data.frame(fit_grow_mix_ant)
mat_grow_mix_ant <- as.matrix(fit_grow_mix_ant)
#print(colnames(posterior_grow_mix_ant))
```

```{r Growth Visualizations}
par(mfrow = c(1,2))
plot(density(posterior_grow_mix_ant$mean_y_rep),
     main = "Simulated Mean and Data Mean")
abline(v = mean(y), col = "red", lty = 2)
plot(density(posterior_grow_mix_ant$sd_y_rep),
     main = "Simulated SD and Data SD")
abline(v = sd(y), col = "red", lty = 2)


grow_mix_ant_mod <- stan_glmer(y ~ vol*ant + (1|year) + (1|plot),warmup = 500, iter = 1000, chains = 1, cores = 2, thin = 1 )
plot_title <- ggtitle("Mixed Ant Effects Growth Model Simulated Data")
bayesplot::ppc_dens_overlay(y = grow_mix_ant_mod$y,
                 yrep = posterior_predict(grow_mix_ant_mod, draws = 50)) + plot_title
```

#### Survival
```{r Survival Ant Mixed Model}
vol = log(data$volume_t)
y = data$Survival_t1
N = nrow(data)
N_ant = 4
ant = data$ant
N_Year <- max(data$year)
N_Plot <- max(data$plot)
plot <- data$plot
year <- data$year
stan_data <- list(N = N, ## number of observations
                  vol = vol, ## predictors volume
                  y = y, ## response volume next year
                  ant = ant,## predictors ants
                  N_ant = N_ant, ## number of ant states
                  N_Year = N_Year, ## number of years
                  N_Plot = N_Plot, ## number of plots
                  plot = plot, ## predictor plots
                  year = year ## predictor years
) 

write("// Stan model for simple ant survival regression

data {
  int <lower = 1> N; // number of observations
  int <lower = 1> N_ant; // number of ant states
  int <lower = 1, upper = N_ant> ant[N]; // the list of ant species 
  vector[N] vol;	//size_t
  int <lower = 0, upper = 1> y[N]; // survival in year t1
  int<lower=1> N_Year; //number of plots
  int<lower=1> N_Plot; //number of years
  int<lower=1, upper=N_Plot> plot[N]; // plot
  int<lower=1, upper=N_Year> year[N]; // year
}
transformed data {
  real<lower = 0> mean_y = mean(to_vector(y));
  real<lower = 0> sd_y = sd(to_vector(y));
}
parameters {
  vector[N_ant] beta0; //intercept, unique to ant sp
  vector[N_ant] beta1; //slope, unique to ant sp
  vector[N_Plot] u; //subject intercepts
  vector[N_Year] w; //item intercepts
  real < lower = 0 > sigma; // Error SD
  real < lower = 0 > sigma_u; // plot SD
  real < lower = 0 > sigma_w; // year SD
}

transformed parameters{
  vector[N] mu; //linear predictor for the mean
  for(i in 1:N){
    mu[i] = beta0[ant[i]] + beta1[ant[i]] * vol[i] + u[plot[i]] + w[year[i]];
  }
}
model {
//Priors
 u ~ normal(0, sigma_u); // plot random effects
 w ~ normal(0, sigma_w); // year random effects
 beta0 ~ normal(0,100); // intercept distribution
 beta1 ~ normal(0,100); // slope distribution
 //Model
 for(i in 1:N){
 y[i] ~ bernoulli_logit(mu[i]);
 }
}
generated quantities {
  int<lower = 0> y_rep[N] = bernoulli_logit_rng(mu);
  real<lower = 0> mean_y_rep = mean(to_vector(y_rep));
  real<lower = 0> sd_y_rep = sd(to_vector(y_rep));
}
",

"surv_ant_mix_lm1.stan")
## Check that you wrote a file
#stanc("surv_ant_mix_lm1.stan")
## Save the file path
stanny <- "surv_ant_mix_lm1.stan"
## Now we fit the model
fit_surv_mix_ant <- stan(file = stanny, data = stan_data, warmup = 5, iter = 10, chains = 1, cores = 2, thin = 1)
fit_surv_mix_ant

#class(fit)
posterior_surv_mix_ant <- as.data.frame(fit_surv_mix_ant)
#print(colnames(posterior_surv_mix_ant))
```

```{r Survival Visualize}
par(mfrow = c(1,2))
plot(density(posterior_surv_mix_ant$mean_y_rep), xlim = c(0.9639, 0.9997))
abline(v = mean(data$Survival_t1), col = "red", lty = 2)
plot(density(posterior_surv_mix_ant$sd_y_rep), xlim = c(0,0.190))
abline(v = sd(data$Survival_t1), col = "red", lty = 2)


surv_mix_ant_mod <- stan_glmer(y ~ vol * ant + (1|plot) + (1|year),warmup = 500, iter = 1000, chains = 1, cores = 2, thin = 1 )
plot_title <- ggtitle("Mixed Ant Effects Survival Model Simulated Data")
bayesplot::ppc_dens_overlay(y = surv_mix_ant_mod$y,
                 yrep = posterior_predict(surv_mix_ant_mod, draws = 50)) + plot_title
```
The mean here is too large and the standard deviation is also too large

#### Total Flowers
```{r}
y <- flower$TotFlowerbuds_t
vol = flower$volume_t
N = nrow(flower)
N_ant = 4
ant = flower$ant
N_Year <- max(flower$year)
N_Plot <- max(flower$plot)
plot <- flower$plot
year <- flower$year
stan_data <- list(N = N, ## number of observations
                  vol = vol, ## predictors volume
                  y = y, ## response volume next year
                  ant = ant,## predictors ants
                  N_ant = N_ant, ## number of ant states
                  N_Year = N_Year, ## number of years
                  N_Plot = N_Plot, ## number of plots
                  plot = plot, ## predictor plots
                  year = year ## predictor years
) 

write("// Stan model for simple total flowers regression

data {
 int <lower = 1> N; // number of observations
  int <lower = 1> N_ant; // number of ant states
  int <lower = 1, upper = N_ant> ant[N]; // the list of ant species 
  vector[N] vol;	//size_t
  int <lower = 0> y[N]; // survival in year t1
  int<lower=1> N_Year; //number of plots
  int<lower=1> N_Plot; //number of years
  int<lower=1, upper=N_Plot> plot[N]; // plot
  int<lower=1, upper=N_Year> year[N]; // year
}
transformed data {
  real<lower = 0> mean_y = mean(to_vector(y));
  real<lower = 0> sd_y = sd(to_vector(y));
}
parameters {
  vector[N_ant] beta0; //intercept, unique to ant sp
  vector[N_ant] beta1; //slope, unique to ant sp
  vector[N_Plot] u; //subject intercepts
  vector[N_Year] w; //item intercepts
  real < lower = 0 > sigma; // Error SD
  real < lower = 0 > sigma_u; // plot SD
  real < lower = 0 > sigma_w; // year SD
}
transformed parameters{
  vector[N] mu; //linear predictor for the mean
  for(i in 1:N){
    mu[i] = beta0[ant[i]] + beta1[ant[i]] * vol[i] + u[plot[i]] + w[year[i]];
  }
}
model {
 // Model
  u ~ normal(0, sigma_u); // plot random effects
  w ~ normal(0, sigma_w); // year random effects
  beta0 ~ normal(0,100); // intercept distribution
  beta1 ~ normal(0,100); // slope distribution
  for(i in 1:N){
    y[i] ~ poisson(mu[i]);
  }
}
generated quantities {
  int<lower = 0> y_rep[N] = poisson_rng(mu);
  real<lower = 0> mean_y_rep = mean(to_vector(y_rep));
  real<lower = 0> sd_y_rep = sd(to_vector(y_rep));
} 
",

"flower_ant_mix_lm1.stan")
## Check that you wrote a file
#stanc("flower_ant_mix_lm1.stan")
## Save the file path
stanny <- "flower_ant_mix_lm1.stan"
## Now we fit the model
fit_flow_mix_ant <- stan(file = stanny, data = stan_data, warmup = 500, iter = 1000, chains = 1, cores = 2, thin = 1)

posterior_flow_mix_ant <- as.data.frame(fit_flow_mix_ant)
```

```{r Total Visualize}
par(mfrow = c(1,2))
plot(density(posterior_flow_mix_ant$mean_y_rep), xlim = c(10.7, 73310))
abline(v = mean(flower$TotFlowerbuds_t), col = "red", lty = 2)
plot(density(posterior_flow_mix_ant$sd_y_rep), xlim = c(0,0.190))
abline(v = sd(flower$TotFlowerbuds_t), col = "red", lty = 2)

flow_mix_ant_mod <- stan_glmer(y ~ 0 + ant*vol + (1|year) + (1|plot),family = "poisson", warmup = 500, iter = 1000, chains = 1, cores = 2, thin = 1 )
plot_title <- ggtitle("Mixed Ant Effects Total Flowerbuds Model Simulated Data")
bayesplot::ppc_dens_overlay(y = flow_mix_ant_mod$y,
                 yrep = posterior_predict(flow_mix_ant_mod, draws = 50)) + plot_title
```

#### Repro
```{r Repro Ant Mixed Model}
vol1 <- flower$volume_t1
y = flower$repro_state_t1
N = nrow(flower)
N_ant = 4
ant = flower$ant
N_Year <- max(flower$year)
N_Plot <- max(flower$plot)
plot <- flower$plot
year <- flower$year
stan_data <- list(N = N, ## number of observations
                  vol1 = vol1, ## predictors volume
                  y = y, ## response volume next year
                  ant = ant,## predictors ants
                  N_ant = N_ant, ## number of ant states
                  N_Year = N_Year, ## number of years
                  N_Plot = N_Plot, ## number of plots
                  plot = plot, ## predictor plots
                  year = year ## predictor years
) 


write("// Stan model for simple total flowers regression

data {
  int <lower = 1> N; // number of observations
  int <lower = 1> N_ant; // number of ant states
  int <lower = 1, upper = N_ant> ant[N]; // the list of ant species 
  vector[N] vol1;	//size_t
  int <lower = 0, upper = 1> y[N]; // survival in year t1
  int<lower=1> N_Year; //number of plots
  int<lower=1> N_Plot; //number of years
  int<lower=1, upper=N_Plot> plot[N]; // plot
  int<lower=1, upper=N_Year> year[N]; // year
}
transformed data {
  real<lower = 0> mean_y = mean(to_vector(y));
  real<lower = 0> sd_y = sd(to_vector(y));
}
parameters {
  vector[N_ant] beta0; //intercept, unique to ant sp
  vector[N_ant] beta1; //slope, unique to ant sp
  vector[N_Plot] u; //subject intercepts
  vector[N_Year] w; //item intercepts
  real < lower = 0 > sigma; // Error SD
  real < lower = 0 > sigma_u; // plot SD
  real < lower = 0 > sigma_w; // year SD
}
transformed parameters{
  vector[N] mu; //linear predictor for the mean
  for(i in 1:N){
    mu[i] = beta0[ant[i]] + beta1[ant[i]] * vol1[i] + u[plot[i]] + w[year[i]];
  }
}
model {
 // Priors
  u ~ normal(0, sigma_u); // plot random effects
  w ~ normal(0, sigma_w); // year random effects
  beta0 ~ normal(0,100); // intercept distribution
  beta1 ~ normal(0,100); // slope distribution
 // Model
 for(i in 1:N){
  y[i] ~ bernoulli_logit(mu[i]);
 }
}
generated quantities {
  int<lower = 0> y_rep[N] = bernoulli_logit_rng(mu);
  real<lower = 0> mean_y_rep = mean(to_vector(y_rep));
  real<lower = 0> sd_y_rep = sd(to_vector(y_rep));
}
",

"repro_ant_mix_lm1.stan")

## Check that you wrote a file
stanc("repro_ant_mix_lm1.stan")
## Save the file path
stanny <- "repro_ant_mix_lm1.stan"
## Now we fit the model
fit_repro_mix_ant <- stan(file = stanny, data = stan_data, warmup = 5, iter = 10, chains = 1, cores = 2, thin = 1)

posterior_repro_mix_ant <- as.data.frame(fit_repro_mix_ant)
```

```{r Reproduction Visualize}
par(mfrow = c(1,2))
plot(density(posterior_repro_mix_ant$mean_y_rep), xlim = c(10.7, 73310))
abline(v = mean(flower$repro_state_t1), col = "red", lty = 2)
plot(density(posterior_repro_mix_ant$sd_y_rep), xlim = c(0,0.190))
abline(v = sd(flower$repro_state_t1), col = "red", lty = 2)

repro_mix_ant_mod <- stan_glmer(y ~ 0 + ant*vol + (1|year) + (1|plot),family = "binomial", warmup = 500, iter = 1000, chains = 1, cores = 2, thin = 1 )
plot_title <- ggtitle("Mixed Ant Effects Reproductive State Model Simulated Data")
bayesplot::ppc_dens_overlay(y = repro_mix_ant_mod$y,
                 yrep = posterior_predict(repro_mix_ant_mod, draws = 50)) + plot_title
```

####Viability Model

```{r Viability model}
good <- flower$Goodbuds_t
abort <- flower$ABFlowerbuds_t
tot <- flower$TotFlowerbuds_t
vol = log(flower$volume_t)
N = nrow(flower)
N_ant = 4
ant = flower$ant
N_Year <- max(flower$year)
N_Plot <- max(flower$plot)
plot <- flower$plot
year <- flower$year
stan_data <- list(N = N, ## number of observations = trials
                  N_ant = N_ant,
                  ant = ant,
                  good = good, ## good buds = successes
                  abort = abort, ## aborted buds data
                  tot = tot, ## number of trials
                  vol = vol,
                  N_Year = N_Year, ## number of years
                  N_Plot = N_Plot, ## number of plots
                  plot = plot, ## predictor plots
                  year = year ## predictor years
) 

write("// Stan model for simple total flowers regression
data {
 int < lower = 1 > N; // Sample size
 int <lower = 0> good[N]; // Number of viable seeds
 int <lower = 1> N_ant; // number of ant states
 int <lower = 1, upper = N_ant> ant[N]; // the list of ant species 
 int<lower=0> tot[N]; // number of trials
 int<lower=0> abort[N];
 vector[N] vol;	//size_t
 int<lower=1> N_Year; //number of plots
  int<lower=1> N_Plot; //number of years
  int<lower=1, upper=N_Plot> plot[N]; // plot
  int<lower=1, upper=N_Year> year[N]; // year
}
transformed data {
  real<lower = 0> mean_y = mean(to_vector(good));
  real<lower = 0> sd_y = sd(to_vector(good));
}
parameters {
  real <lower = 0, upper = 1> theta[N]; // probability of viability for each bud
  //
  real<lower=0,upper=1> v0;
  vector[N_Plot] u; //subject intercepts
  vector[N_Year] w; //item intercepts
  real < lower = 0 > sigma; // Error SD
  real < lower = 0 > sigma_u; // plot SD
  real < lower = 0 > sigma_w; // year SD
}
transformed parameters{
  real<lower=0,upper=1> predV[N]; // proportion viable for each plant?
  // Prediction for seed viability
  for(i in 1:N){
    predV[i] = v0 * pow(theta[ant[i]],good[i]) * (1-theta[ant[i]])^abort[i];
  }
}
model {
 // Priors
 v0  ~ beta(10,1);  // intercept viability model
  u ~ normal(0, sigma_u); // plot random effects
  w ~ normal(0, sigma_w); // year random effects
  theta ~ normal(0,100); // intercept distribution
  
  good ~ binomial(tot, predV);
}
generated quantities {
  int<lower = 0> y_rep[N] = binomial_rng(tot,predV);
  real<lower = 0> mean_y_rep = mean(to_vector(y_rep));
  real<lower = 0> sd_y_rep = sd(to_vector(y_rep));
}
", "viab_mix_ant.stan")
## Check that you wrote a file
stanc("viab_mix_ant.stan")
## Save the file path
stanny <- "viab_mix_ant.stan"
## Now we fit the model
fit_viab_mix_ant <- stan(file = stanny, data = stan_data, warmup = 5, iter = 10, chains = 1, cores = 2, thin = 1)


posterior_viab_mix_ant <- as.data.frame(fit_viab_mix_ant)
```

```{r Viability Visualize}
par(mfrow = c(1,2))
plot(density(posterior_viab_mix_ant$mean_y_rep), xlim = c(2.19,10))
abline(v = mean(flower$Goodbuds_t), col = "red", lty = 2)
plot(density(posterior_viab_mix_ant$sd_y_rep), xlim = c(3.3,8.7))
abline(v = sd(flower$Goodbuds_t), col = "red", lty = 2)

viab_mix_ant_mod <- stan_glmer(cbind(flower$Goodbuds_t,flower$ABFlowerbuds_t) ~ flower$ant + (1|flower$year) + (1|flower$plot),family = "binomial", warmup = 5, iter = 10, chains = 1, cores = 2, thin = 1 )
plot_title <- ggtitle("Mixed Ant Effects Viability Model Simulated Data")
bayesplot::ppc_dens_overlay(y = viab_mix_ant_mod$y,
                 yrep = posterior_predict(viab_mix_ant_mod, draws = 5)) + plot_title
```

```{r}
lm_alpha_other <- summary(viab_model_ant_interact)$coeff[1]  # the intercept
lm_alpha_crem <- summary(viab_model_ant_interact)$coeff[3]
lm_alpha_liom <- summary(viab_model_ant_interact)$coeff[4]
lm_alpha_vacant <- summary(viab_model_ant_interact)$coeff[5]
lm_beta_other <- summary(viab_model_ant_interact)$coeff[2]  # the slope
lm_beta_crem <- summary(viab_model_ant_interact)$coeff[6]
lm_beta_liom <- summary(viab_model_ant_interact)$coeff[7]
lm_beta_vacant <- summary(viab_model_ant_interact)$coeff[8]

par(mfrow = c(1,2))
#Plot Slopes
plot(density(posterior_viab_ant$`theta[1]`), main = "Viability Slope Distributions", col = "black", lwd = 2, xlim = c(-1,3), ylim =  c(0,2))
abline(v = lm_alpha_other, col = "black", lty = 2)
lines(density(posterior_viab_ant$`theta[2]`),  col = "red")
abline(v = lm_alpha_crem, col = "red", lty = 2)
lines(density(posterior_viab_ant$`theta[3]`),col = "blue", lwd = 2)
abline(v = lm_alpha_liom, col = "blue", lty = 2)
lines(density(posterior_viab_ant$`theta[4]`), col = "pink", lwd = 2)
abline(v = lm_alpha_vacant, col = "pink", lty = 2)
legend("topleft", legend = c("other","Crem.", "Liom.","Vac"), col = c("black","red","blue","pink"), lty = 1)
```

## Multinomial
#### 1
```{r}
N <- nrow(data)
vol = log(data$volume_t)
ant <- data$ant
N_ant <- length(unique(data$ant))
y <- data$ant1
N_Year <- max(data$year)
N_Plot <- max(data$plot)
plot <- data$plot
year <- data$year
stan_data <- list(N = N, ## number of observations
                  N_ant = N_ant, ## number of ants
                  K = K, ## number of covariates (only volume I think)
                  vol = vol, ## Volume in year t
                  y = y, ## ant state in year t1
                  N_Year = N_Year,
                  N_Plot = N_Plot,
                  year = year,
                  plot = plot,
                  ant = ant ## ant state in year t
)
write("
data {
    int<lower=2> N_ant; // of alternatives/outcomes
    int<lower=1> N; // of observations
    int <lower=0,upper=N_ant> y[N];
    int <lower = 1, upper = N_ant> ant[N]; // the list of ant species 
    vector[N] vol;
    int<lower=1> N_Year; //number of plots
    int<lower=1> N_Plot; //number of years
    int<lower=1, upper=N_Plot> plot[N]; // plot
    int<lower=1, upper=N_Year> year[N]; // year
}
transformed data {
  real<lower = 0> mean_y = mean(to_vector(y));
  real<lower = 0> sd_y = sd(to_vector(y));
}
parameters {
  vector[N_ant] beta0; //intercept, unique to ant sp
  vector[N_ant] beta1; //slope, unique to ant sp
  vector[N_Plot] u; //subject intercepts
  vector[N_Year] w; //item intercepts
  real < lower = 0 > sigma; // Error SD
  real < lower = 0 > sigma_u; // plot SD
  real < lower = 0 > sigma_w; // year SD

}
transformed parameters{
  vector[N] mu; //linear predictor for the mean
  for(i in 1:N){
    mu[i] = beta0[ant[i]]  + u[plot[i]] + w[year[i]];
  }
}
model {
    y ~ categorical_logit(mu);
}
generated quantities {
  int<lower = 0> y_rep[N] = bernoulli_logit_rng(mu);
  real<lower = 0> mean_y_rep = mean(to_vector(y_rep));
  real<lower = 0> sd_y_rep = sd(to_vector(y_rep));
}
",
"multinomial1.stan")
#stanc("multinomial1.stan")
## Save the file path
stanny <- "multinomial1.stan"
## Now we fit the model
fit_multi1 <- stan(file = stanny, data = stan_data, warmup = 5, iter = 10, chains = 1, cores = 2, thin = 1)
#class(fit)
posterior_multi1 <- as.data.frame(fit_multi1)
```

```{r 1 Visualize}
par(mfrow = c(1,2))
plot(density(posterior_multi1$mean_y_rep), xlim = c(10.7, 73310))
abline(v = mean(data$ant1), col = "red", lty = 2)
plot(density(posterior_multi1$sd_y_rep), xlim = c(0,0.190))
abline(v = sd(data$ant1), col = "red", lty = 2)

multi1_mod <- stan_glmer(y ~ 0 + ant + (1|year) + (1|plot), warmup = 5, iter = 10, chains = 1, cores = 2, thin = 1 )
plot_title <- ggtitle("Mixed Ant T1 State Model Simulated Data")
bayesplot::ppc_dens_overlay(y = multi1_mod$y,
                 yrep = posterior_predict(multi1_mod, draws = 5)) + plot_title
```


#### 2
```{r}
N <- nrow(data)
vol = log(data$volume_t)
ant <- data$ant
N_ant <- length(unique(data$ant))
y <- data$ant1
N_Year <- max(data$year)
N_Plot <- max(data$plot)
plot <- data$plot
year <- data$year
stan_data <- list(N = N, ## number of observations
                  N_ant = N_ant, ## number of ants
                  K = K, ## number of covariates (only volume I think)
                  vol = vol, ## Volume in year t
                  y = y, ## ant state in year t1
                  N_Year = N_Year,
                  N_Plot = N_Plot,
                  year = year,
                  plot = plot,
                  ant = ant ## ant state in year t
)
write("
data {
    int<lower=2> N_ant; // of alternatives/outcomes
    int<lower=1> N; // of observations
    int <lower=0,upper=N_ant> y[N];
    int <lower = 1, upper = N_ant> ant[N]; // the list of ant species 
    vector[N] vol;
    int<lower=1> N_Year; //number of plots
    int<lower=1> N_Plot; //number of years
    int<lower=1, upper=N_Plot> plot[N]; // plot
    int<lower=1, upper=N_Year> year[N]; // year
}
transformed data {
  real<lower = 0> mean_y = mean(to_vector(y));
  real<lower = 0> sd_y = sd(to_vector(y));
}
parameters {
  vector[N_ant] beta0; //intercept, unique to ant sp
  real beta1; //slope, unique to ant sp
  vector[N_Plot] u; //subject intercepts
  vector[N_Year] w; //item intercepts
  real < lower = 0 > sigma; // Error SD
  real < lower = 0 > sigma_u; // plot SD
  real < lower = 0 > sigma_w; // year SD

}
transformed parameters{
  vector[N] mu; //linear predictor for the mean
  for(i in 1:N){
    mu[i] = beta0[ant[i]] + beta1 * vol[i] + u[plot[i]] + w[year[i]];
  }
}
model {
    y ~ categorical_logit(mu);
}
generated quantities {
  int<lower = 0> y_rep[N] = bernoulli_logit_rng(mu);
  real<lower = 0> mean_y_rep = mean(to_vector(y_rep));
  real<lower = 0> sd_y_rep = sd(to_vector(y_rep));
}
",
"multinomial2.stan")
stanc("multinomial2.stan")
## Save the file path
stanny <- "multinomial2.stan"
## Now we fit the model
fit_multi2 <- stan(file = stanny, data = stan_data, warmup = 5, iter = 10, chains = 1, cores = 2, thin = 1)
#class(fit)
posterior_multi2 <- as.data.frame(fit_multi2)
```

```{r 2 Visualize}
par(mfrow = c(1,2))
plot(density(posterior_multi2$mean_y_rep), xlim = c(10.7, 73310))
abline(v = mean(data$ant1), col = "red", lty = 2)
plot(density(posterior_multi2$sd_y_rep), xlim = c(0,0.190))
abline(v = sd(data$ant1), col = "red", lty = 2)

multi2_mod <- stan_glmer(y ~ 0 + ant + vol + (1|year) + (1|plot), warmup = 5, iter = 10, chains = 1, cores = 2, thin = 1 )
plot_title <- ggtitle("Mixed Ant Effects Ant T1 State Model Simulated Data")
bayesplot::ppc_dens_overlay(y = multi2_mod$y,
                 yrep = posterior_predict(multi2_mod, draws = 5)) + plot_title
```

```{r}
N <- nrow(data)
vol = log(data$volume_t)
ant <- data$ant
N_ant <- length(unique(data$ant))
y <- data$ant1
N_Year <- max(data$year)
N_Plot <- max(data$plot)
plot <- data$plot
year <- data$year
stan_data <- list(N = N, ## number of observations
                  N_ant = N_ant, ## number of ants
                  K = K, ## number of covariates (only volume I think)
                  vol = vol, ## Volume in year t
                  y = y, ## ant state in year t1
                  N_Year = N_Year,
                  N_Plot = N_Plot,
                  year = year,
                  plot = plot,
                  ant = ant ## ant state in year t
)
write("
data {
    int<lower=2> N_ant; // of alternatives/outcomes
    int<lower=1> N; // of observations
    int <lower=0,upper=N_ant> y[N];
    int <lower = 1, upper = N_ant> ant[N]; // the list of ant species 
    vector[N] vol;
    int<lower=1> N_Year; //number of plots
    int<lower=1> N_Plot; //number of years
    int<lower=1, upper=N_Plot> plot[N]; // plot
    int<lower=1, upper=N_Year> year[N]; // year
}
transformed data {
  real<lower = 0> mean_y = mean(to_vector(y));
  real<lower = 0> sd_y = sd(to_vector(y));
}
parameters {
  vector[N_ant] beta0; //intercept, unique to ant sp
  vector[N_ant] beta1; //slope, unique to ant sp
  vector[N_Plot] u; //subject intercepts
  vector[N_Year] w; //item intercepts
  real < lower = 0 > sigma; // Error SD
  real < lower = 0 > sigma_u; // plot SD
  real < lower = 0 > sigma_w; // year SD

}
transformed parameters{
  vector[N] mu; //linear predictor for the mean
  for(i in 1:N){
    mu[i] = beta0[ant[i]] + beta1[ant[i]] * vol[i] + u[plot[i]] + w[year[i]];
  }
}
model {
    y ~ categorical_logit(mu);
}
generated quantities {
  int<lower = 0> y_rep[N] = bernoulli_logit_rng(mu);
  real<lower = 0> mean_y_rep = mean(to_vector(y_rep));
  real<lower = 0> sd_y_rep = sd(to_vector(y_rep));
}
",
"multinomial3.stan")
#stanc("multinomial3.stan")
## Save the file path
stanny <- "multinomial3.stan"
## Now we fit the model
fit_multi3 <- stan(file = stanny, data = stan_data, warmup = 5, iter = 10, chains = 1, cores = 2, thin = 1)
#class(fit)
posterior_multi3 <- as.data.frame(fit_multi3)
```

```{r 3 Visualize}
par(mfrow = c(1,2))
plot(density(posterior_multi3$mean_y_rep), xlim = c(10.7, 73310))
abline(v = mean(data$ant1), col = "red", lty = 2)
plot(density(posterior_multi3$sd_y_rep), xlim = c(0,0.190))
abline(v = sd(data$ant1), col = "red", lty = 2)

multi3_mod <- stan_glmer(y ~ 0 + ant*vol + (1|year) + (1|plot), warmup = 5, iter = 10, chains = 1, cores = 2, thin = 1 )
plot_title <- ggtitle("Mixed Ant Interaction Effects Ant T1 State Model Simulated Data")
bayesplot::ppc_dens_overlay(y = multi3_mod$y,
                 yrep = posterior_predict(multi3_mod, draws = 5)) + plot_title
```

```{r Viability model}
y_good <- flower$Goodbuds_t
y_abort <- flower$ABFlowerbuds_t
y_tot <- flower$TotFlowerbuds_t
vol = log(flower$volume_t)
N = nrow(flower)
N_ant = 4
ant = flower$ant
N_Year <- max(flower$year)
N_Plot <- max(flower$plot)
plot <- flower$plot
year <- flower$year
stan_data <- list(N = N, ## number of observations = trials
                  N_ant = N_ant,
                  ant = ant,
                  y_good = y_good, ## good buds = successes
                  y_abort = y_abort, ## aborted buds data
                  y_tot = y_tot, ## number of trials
                  N_Year = N_Year,
                  N_Plot = N_Plot,
                  year = year,
                  plot = plot,
                  vol = vol
) 

write("// Stan model for simple total flowers regression
data {
 int < lower = 1 > N; // Sample size
 int <lower = 0> y_good[N]; // Number of viable seeds
 int <lower = 1> N_ant; // number of ant states
 int <lower = 1, upper = N_ant> ant[N]; // the list of ant species 
 int<lower=0> y_tot[N]; // number of trials
 vector[N] vol;	//size_t
 int<lower=1> N_Year; //number of plots
 int<lower=1> N_Plot; //number of years
 int<lower=1, upper=N_Plot> plot[N]; // plot
 int<lower=1, upper=N_Year> year[N]; // year
}
transformed data {
  real<lower = 0> mean_y = mean(to_vector(y_good));
  real<lower = 0> sd_y = sd(to_vector(y_good));
}
parameters {
  vector[N] beta0; //slope, unique to ant sp
  vector[N_Plot] u; //subject intercepts
  vector[N_Year] w; //item intercepts
  real < lower = 0 > sigma; // Error SD
  real < lower = 0 > sigma_u; // plot SD
  real < lower = 0 > sigma_w; // year SD
}
transformed parameters{
  real<lower=0,upper=1> predV[N];
  // Prediction for seed viability
  for(i in 1:N){
    predV[i] = beta0[ant[i]] + u[plot[i]] + w[year[i]];
  }
}
model {
 // Priors
 u ~ normal(0, sigma_u); // plot random effects
  w ~ normal(0, sigma_w); // year random effects
 beta0 ~ normal (0,100);
  y_good ~ binomial(y_tot, predV);
}
generated quantities {
  int<lower = 0> y_rep[N] = binomial_rng(mu);
  real<lower = 0> mean_y_rep = mean(to_vector(y_rep));
  real<lower = 0> sd_y_rep = sd(to_vector(y_rep));
}
", "viab_mix_ant.stan")
## Check that you wrote a file
#stanc("viab_ant.stan")
## Save the file path
stanny <- "viab_mix_ant.stan"
## Now we fit the model
fit_viab_mix_ant <- stan(file = stanny, data = stan_data, warmup = 5, iter = 10, chains = 1, cores = 2, thin = 1)


posterior_viab_mix_ant <- as.data.frame(fit_viab_mix_ant)
```