---
title: "Multinomial Models"
author: "Ali Campbell"
date: "2/8/2021"
output: html_document
---

```{r setup, include=FALSE}
library(rstanarm)
library(brms)  # for models
library(tidyverse)
library(rstan)
library(StanHeaders)
library(shinystan)
#library(bayesplot)
library(devtools)
library(tidyr)
library(lattice)
library(lme4)
library(dplyr)
library(tidyverse)
library(nnet)
library(fixest)
library(mlogit)
library(dfidx)
library(effects)
library(bbmle)
library(magrittr)
library(Gmisc)
library(RColorBrewer)
library(ggeffects)
library(heplots)
library("posterior")
#library(sjPlot)
knitr::opts_chunk$set(echo = TRUE)
options(mc.cores = parallel::detectCores())
setwd("/Users/alicampbell/Box Sync/Grad/Cactus/Shared Code/ant_cactus_demography/Stan")
```

#### Data


#### Data

```{r}
## Data Set
cactus$ant_t1_relevel <- relevel(cactus$ant_t1,ref = "vacant")
data <- cactus[ ,c("Plot","Year_t","Survival_t1","ant_t","ant_t1","volume_t","volume_t1","repro_state_t1", "ant_t1_relevel")]
data <- na.omit(data)
data$ant <- as.integer(data$ant_t)
data$ant1 <- as.integer(data$ant_t1_relevel)
## add columns for each ant classification so they can be binary
data$crem <- 0 ##2
data$liom <- 0 ##3
data$other <- 0 ##1
data$vacant <- 0 ##4
for(i in 1:nrow(data)){
  if(data$ant[i] == 1){data$other[i] <- 1}
  if(data$ant[i] == 2){data$crem[i] <- 1}
  if(data$ant[i] == 3){data$liom[i] <- 1}
  if(data$ant[i] == 4){data$vacant[i] <- 1}
}
data$Year_t <- as.factor(data$Year_t)
data$year <- as.integer(data$Year_t)
data$Plot <- as.factor(data$Plot)
data$plot <- as.integer(data$Plot)


## Flower Data Set
flower <- cactus[ , c("TotFlowerbuds_t","ABFlowerbuds_t","Goodbuds_t","ant_t", "repro_state_t1","volume_t","volume_t1","Year_t","Plot")]
flower <- na.omit(flower)
flower$ant <- as.integer(flower$ant_t)
flower$Year_t <- as.factor(flower$Year_t)
flower$year <- as.integer(flower$Year_t)
flower$Plot <- as.factor(flower$Plot)
flower$plot <- as.integer(flower$Plot)
```


#### 1
```{r}
N <- nrow(data)
vol = log(data$volume_t)
ant <- data$ant
N_ant <- length(unique(data$ant))
y <- data$ant1
N_Year <- max(data$year)
N_Plot <- max(data$plot)
plot <- data$plot
year <- data$year
stan_data <- list(N = N, ## number of observations
                  N_ant = N_ant, ## number of ants
                  K = K, ## number of covariates (only volume I think)
                  vol = vol, ## Volume in year t
                  y = y, ## ant state in year t1
                  N_Year = N_Year,
                  N_Plot = N_Plot,
                  year = year,
                  plot = plot,
                  ant = ant ## ant state in year t
)
write("
data {
    int<lower=2> N_ant; // of alternatives/outcomes
    int<lower=1> N; // of observations
    int <lower=0,upper=N_ant> y[N];
    int <lower = 1, upper = N_ant> ant[N]; // the list of ant species 
    vector[N] vol;
    int<lower=1> N_Year; //number of plots
    int<lower=1> N_Plot; //number of years
    int<lower=1, upper=N_Plot> plot[N]; // plot
    int<lower=1, upper=N_Year> year[N]; // year
}
transformed data {
  real<lower = 0> mean_y = mean(to_vector(y));
  real<lower = 0> sd_y = sd(to_vector(y));
}
parameters {
  vector[N_ant] beta0; //intercept, unique to ant sp
  vector[N_ant] beta1; //slope, unique to ant sp
  vector[N_Plot] u; //subject intercepts
  vector[N_Year] w; //item intercepts
  real < lower = 0 > sigma; // Error SD
  real < lower = 0 > sigma_u; // plot SD
  real < lower = 0 > sigma_w; // year SD

}
transformed parameters{
  vector[N] mu; //linear predictor for the mean
  for(i in 1:N){
    mu[i] = beta0[ant[i]]  + u[plot[i]] + w[year[i]];
  }
}
model {
    y ~ categorical_logit(mu);
}
generated quantities {
  int<lower = 0> y_rep[N] = bernoulli_logit_rng(mu);
  real<lower = 0> mean_y_rep = mean(to_vector(y_rep));
  real<lower = 0> sd_y_rep = sd(to_vector(y_rep));
}
",
"multinomial1.stan")
#stanc("multinomial1.stan")
## Save the file path
stanny <- "multinomial1.stan"
## Now we fit the model
fit_multi1 <- stan(file = stanny, data = stan_data, warmup = 5, iter = 10, chains = 4, cores = 2, thin = 1)
#class(fit)
posterior_multi1 <- as.data.frame(fit_multi1)
```


#### 2 Ants no interaction
```{r}
N <- nrow(data)
vol = log(data$volume_t)
ant <- data$ant
N_ant <- length(unique(data$ant))
y <- data$ant1
N_Year <- max(data$year)
N_Plot <- max(data$plot)
plot <- data$plot
year <- data$year
stan_data <- list(N = N, ## number of observations
                  N_ant = N_ant, ## number of ants
                  K = K, ## number of covariates (only volume I think)
                  vol = vol, ## Volume in year t
                  y = y, ## ant state in year t1
                  N_Year = N_Year,
                  N_Plot = N_Plot,
                  year = year,
                  plot = plot,
                  ant = ant ## ant state in year t
)
write("
data {
    int<lower=2> N_ant; // of alternatives/outcomes
    int<lower=1> N; // of observations
    int <lower=0,upper=N_ant> y[N];
    int <lower = 1, upper = N_ant> ant[N]; // the list of ant species 
    vector[N] vol;
    int<lower=1> N_Year; //number of plots
    int<lower=1> N_Plot; //number of years
    int<lower=1, upper=N_Plot> plot[N]; // plot
    int<lower=1, upper=N_Year> year[N]; // year
}
transformed data {
  real<lower = 0> mean_y = mean(to_vector(y));
  real<lower = 0> sd_y = sd(to_vector(y));
}
parameters {
  vector[N_ant] beta0; //intercept, unique to ant sp
  real beta1; //slope, unique to ant sp
  vector[N_Plot] u; //subject intercepts
  vector[N_Year] w; //item intercepts
  real < lower = 0 > sigma; // Error SD
  real < lower = 0 > sigma_u; // plot SD
  real < lower = 0 > sigma_w; // year SD

}
transformed parameters{
  vector[N] mu; //linear predictor for the mean
  for(i in 1:N){
    mu[i] = beta0[ant[i]] + beta1 * vol[i] + u[plot[i]] + w[year[i]];
  }
}
model {
    y ~ categorical_logit(mu);
}
generated quantities {
  int<lower = 0> y_rep[N] = bernoulli_logit_rng(mu);
  real<lower = 0> mean_y_rep = mean(to_vector(y_rep));
  real<lower = 0> sd_y_rep = sd(to_vector(y_rep));
}
",
"multinomial2.stan")
stanc("multinomial2.stan")
## Save the file path
stanny <- "multinomial2.stan"
## Now we fit the model
fit_multi2 <- stan(file = stanny, data = stan_data, warmup = 5, iter = 10, chains = 1, cores = 2, thin = 1)
#class(fit)
posterior_multi2 <- as.data.frame(fit_multi2)
```


#### 3

```{r}
N <- nrow(data)
vol = log(data$volume_t)
ant <- data$ant
N_ant <- length(unique(data$ant))
y <- data$ant1
N_Year <- max(data$year)
N_Plot <- max(data$plot)
plot <- data$plot
year <- data$year
stan_data <- list(N = N, ## number of observations
                  N_ant = N_ant, ## number of ants
                  K = K, ## number of covariates (only volume I think)
                  vol = vol, ## Volume in year t
                  y = y, ## ant state in year t1
                  N_Year = N_Year,
                  N_Plot = N_Plot,
                  year = year,
                  plot = plot,
                  ant = ant ## ant state in year t
)
write("
data {
    int<lower=2> N_ant; // of alternatives/outcomes
    int<lower=1> N; // of observations
    int <lower=0,upper=N_ant> y[N];
    int <lower = 1, upper = N_ant> ant[N]; // the list of ant species 
    vector[N] vol;
    int<lower=1> N_Year; //number of plots
    int<lower=1> N_Plot; //number of years
    int<lower=1, upper=N_Plot> plot[N]; // plot
    int<lower=1, upper=N_Year> year[N]; // year
}
transformed data {
  real<lower = 0> mean_y = mean(to_vector(y));
  real<lower = 0> sd_y = sd(to_vector(y));
}
parameters {
  vector[N_ant] beta0; //intercept, unique to ant sp
  vector[N_ant] beta1; //slope, unique to ant sp
  vector[N_Plot] u; //subject intercepts
  vector[N_Year] w; //item intercepts
  real < lower = 0 > sigma; // Error SD
  real < lower = 0 > sigma_u; // plot SD
  real < lower = 0 > sigma_w; // year SD

}
transformed parameters{
  vector[N] mu; //linear predictor for the mean
  for(i in 1:N){
    mu[i] = beta0[ant[i]] + beta1[ant[i]] * vol[i] + u[plot[i]] + w[year[i]];
  }
}
model {
    y ~ categorical_logit(mu);
}
generated quantities {
  int<lower = 0> y_rep[N] = bernoulli_logit_rng(mu);
  real<lower = 0> mean_y_rep = mean(to_vector(y_rep));
  real<lower = 0> sd_y_rep = sd(to_vector(y_rep));
}
",
"multinomial3.stan")
#stanc("multinomial3.stan")
## Save the file path
stanny <- "multinomial3.stan"
## Now we fit the model
fit_multi3 <- stan(file = stanny, data = stan_data, warmup = 5, iter = 10, chains = 1, cores = 2, thin = 1)
#class(fit)
posterior_multi3 <- as.data.frame(fit_multi3)
```
