---
title: "Stan Practice"
author: "Ali Campbell"
date: "1/13/2021"
output: html_document
---

```{r setup, include=FALSE}
library(rstanarm)
library(brms)  # for models
library(tidyverse)
library(rstan)
library(StanHeaders)
library(shinystan)
#library(bayesplot)
library(devtools)
library(tidyr)
library(lattice)
library(lme4)
library(dplyr)
library(tidyverse)
library(nnet)
library(fixest)
library(mlogit)
library(dfidx)
library(effects)
library(bbmle)
library(magrittr)
library(Gmisc)
library(RColorBrewer)
library(ggeffects)
library(heplots)
library("posterior")
#library(sjPlot)
knitr::opts_chunk$set(echo = TRUE)
options(mc.cores = parallel::detectCores())
setwd("/Users/alicampbell/Box Sync/Grad/Cactus/Shared Code/ant_cactus_demography/Stan")
```

#### Data

```{r}
data <- cactus[ ,c("Plot","Year_t","Survival_t1","ant_t","ant_t1","volume_t","volume_t1","repro_state_t1")]
data <- na.omit(data)
data$ant <- as.integer(data$ant_t)
## add columns for each ant classification so they can be binary
data$crem <- 0 ##2
data$liom <- 0 ##3
data$other <- 0 ##1
data$vacant <- 0 ##4
for(i in 1:nrow(data)){
  if(data$ant[i] == 1){data$other[i] <- 1}
  if(data$ant[i] == 2){data$crem[i] <- 1}
  if(data$ant[i] == 3){data$liom[i] <- 1}
  if(data$ant[i] == 4){data$vacant[i] <- 1}
}
data$Year_t <- as.factor(data$Year_t)
data$year <- as.integer(data$Year_t)
data$Plot <- as.factor(data$Plot)
data$plot <- as.integer(data$Plot)

flower <- cactus[ , c("TotFlowerbuds_t","ABFlowerbuds_t","Goodbuds_t","ant_t", "repro_state_t1","volume_t","volume_t1")]
flower <- na.omit(flower)
flower$ant <- as.integer(flower$ant_t)
```

## Basic Models (No Ant Effects)
####Growth
```{r Growth Model}
## Now rename variables and index
vol <- data$volume_t
y <- data$volume_t1
N <- as.integer(nrow(data))
## Rerun linear model with that new data
#mod1 <- lm(y~x, data = data)
#summary(grow_model)
#summary(mod1)
## Now we can extract some important statistics
lm_alpha <- summary(grow_model)$coeff[1]  # the intercept
lm_beta <- summary(grow_model)$coeff[2]  # the slope
lm_sigma <- sigma(grow_model)  # the residual error
## Make it a dataframe
stan_data <- list(N = N, vol = vol, y = y)
## Write the model in stan
#note that we are using flat priors here which are non restrictive
write("// Stan model for simple growth regression

data {
 int < lower = 1 > N; // Sample size
 vector[N] vol; // Predictor
 vector[N] y; // Outcome
}

parameters {
 real alpha; // Intercept
 real beta; // Slope (regression coefficients)
 real < lower = 0 > sigma; // Error SD
}

model {
// Priors
alpha ~ normal(0,100);
beta ~ normal(0,100); 
//sigma ~ exponential(0,0);
 y ~ normal(alpha + vol * beta , sigma); // The Model
}

generated quantities {
} // The posterior predictive distribution",

"grow_lm1.stan")
## Check that you wrote a file
#stanc("grow_lm1.stan")
## Save the file path
stanny <- "grow_lm1.stan"
## Now we fit the model
fit_grow <- stan(file = stanny, data = stan_data, warmup = 500, iter = 1000, chains = 1, cores = 2, thin = 1)
fit_grow
#class(fit)
posterior_grow <- as.data.frame(fit_grow)
print(colnames(posterior_grow))

par(mfrow = c(1,3))
plot(density(posterior_grow$alpha), main = "Alpha")
abline(v = lm_alpha, col = 4, lty = 2)
plot(density(posterior_grow$beta), main = "Beta", xlim = c(0.85,0.93))
abline(v = lm_beta, col = 4, lty = 2)
plot(density(posterior_grow$sigma), main = "Sigma")
abline(v = lm_sigma, col = 4, lty = 2)
```

####Total Flowers
```{r Total Flowers}
## Ok so this one is difficult because the data does not include this variable because of all of the NAs. 
## Ok so I have created a second data set. Obviously this will be a problem down the line when it all has to go into one model, but here we go for now. 
## Next problem is that the dimensions do not work now. 
y <- flower$TotFlowerbuds_t
N <- nrow(flower)
stan_data <- list(N = N, ## number of observations
                  y = y ## response survival next year
                  ) 

write("// Stan model for simple total flowers regression

data {
 int < lower = 1 > N; // Sample size
 int y[N]; // Outcome
}
parameters {
  real lambda; //intercept, unique to ant
}
model {
// Priors
 lambda ~ beta(1,1);
 // Model
 y ~ poisson(lambda);
}
",

"flower_lm1.stan")
## Check that you wrote a file
stanc("flower_lm1.stan")
## Save the file path
stanny <- "flower_lm1.stan"
## Now we fit the model
fit_flow <- stan(file = stanny, data = stan_data, warmup = 500, iter = 1000, chains = 1, cores = 2, thin = 1)
fit_flow

posterior_flow <- as.data.frame(fit_flow)
print(colnames(posterior_flow))

plot(density(posterior_flow$lambda), main = "Lambda")
abline(v = lm_lambda, col = 4, lty = 2)
```
####Viability
```{r Viability model}
y_good <- flower$Goodbuds_t
y_abort <- flower$AbABFlowerbuds_t
y_tot <- flower$TTotFlowerbuds_t
vol = log(flower$volume_t)
N = nrow(flower)
stan_data <- list(N = N, ## number of observations = trials
                  y_good = y_good, ## good buds = successes
                  y_abort = y_abort, ## aborted buds data
                  y_tot = y_tot, ## number of trials
                  vol = vol
                  ) 

write("// Stan model for simple total flowers regression

data {
 int < lower = 1 > N; // Sample size
 int <lower = 0> y_good[N]; // Number of viable seeds
 int<lower=0> y_tot[N]; // number of trials
 vector[N] vol;	//size_t
}
parameters {
  real beta0; //intercept, unique to ant sp
  real beta1; //slope, unique to ant sp
  real<lower = 0> sigma;
  real<lower=0,upper=1> v0;
  real<lower=0> a_v;
}
transformed parameters{
  real<lower=0,upper=1> predV[n_v];
  for(i in 1:N){
    predV[i] = v0 * (1 - pow(SR_v[i],a_v) ) + 0.00001;
  }
}
model {
 // Priors
 beta0 ~ normal(0,100);
 beta1 ~ normal(0,100); 
 // Model
 y ~ binomial_logit(beta0 + beta1 * vol);
}
",

"viab_lm1.stan")
## Check that you wrote a file
stanc("vian_lm1.stan")
## Save the file path
stanny <- "viab_lm1.stan"
## Now we fit the model
fit_viab <- stan(file = stanny, data = stan_data, warmup = 500, iter = 1000, chains = 1, cores = 2, thin = 1)


posterior_viab <- as.data.frame(fit_viab)
```


####Survival
```{r Survival}
vol = data$volume_t
y <- data$Survival_t1
N <- nrow(data)
#import things from the r regression models for comparison
lm_alpha <- summary(surv_model)$coeff[1]  # the intercept
lm_beta <- summary(surv_model)$coeff[2]  # the slope
summary(surv_model)
## Make it a dataframe
stan_data <- list(N = N, x = x, y = y)
## Write the model in stan
#note that we are using flat priors here which are non restrictive
write("// Stan model for simple survival regression

data {
  int <lower=0> N;
  vector[N] vol;
  int <lower=0,upper=1> y[N];
}
parameters {
  real alpha;
  real beta;
}
model {
 // Priors
 alpha ~ normal(0,100);
 beta ~ normal(0,100); 
 // Model
 y ~ bernoulli_logit(alpha + beta * vol);
}
",

"surv_lm1.stan")
## Check that you wrote a file
stanc("surv_lm1.stan")
## Save the file path
stanny <- "surv_lm1.stan"
## Now we fit the model
fit_surv <- stan(file = stanny, data = stan_data, warmup = 500, iter = 1000, chains = 1, cores = 2, thin = 1)
fit_surv

posterior_surv <- as.data.frame(fit_surv)
print(colnames(posterior_surv))


par(mfrow = c(1,2))

plot(density(posterior_surv$alpha), main = "Alpha")
abline(v = lm_alpha, col = 4, lty = 2)

plot(density(posterior_surv$beta), main = "Beta")
abline(v = lm_beta, col = 4, lty = 2)
```

####Repro

```{r}
vol1 <- flower$volume_t1
y = flower$repro_state_t1
N = nrow(flower)
stan_data <- list(N = N, ## number of observations
                  y = y, ## response survival next year
                  vol1 = vol1
                  ) 

write("// Stan model for simple total flowers regression

data {
 int < lower = 1 > N; // Sample size
 int <lower = 0, upper = 1> y[N]; // Outcome
 vector[N] vol1;	//size_t
}
parameters {
  real beta0; //intercept, unique to ant sp
  real beta1; //slope, unique to ant sp
  real<lower = 0> sigma;
}
model {
 // Priors
 beta0 ~ normal(0,100);
 beta1 ~ normal(0,100); 
 // Model
 y ~ bernoulli_logit(beta0 + beta1 * vol1);
}
",

"repro_lm1.stan")

## Check that you wrote a file
stanc("repro_lm1.stan")
## Save the file path
stanny <- "repro_lm1.stan"
## Now we fit the model
fit_repro <- stan(file = stanny, data = stan_data, warmup = 500, iter = 1000, chains = 1, cores = 2, thin = 1)
fit_repro

posterior_repro <- as.data.frame(fit_repro)
print(colnames(posterior_repro))
```


## Include ants
####Growth
```{r Growth Model}
vol = data$volume_t
y = data$volume_t1
N = nrow(data)
N_ant = 4
ant = data$ant
stan_data <- list(N = N, ## number of observations
                  vol = vol, ## predictors volume
                  y = y, ## response volume next year
                  ant = ant,## predictors ants
                  N_ant = N_ant
                  ) 
## Write the model in stan
#note that we are using flat priors here which are non restrictive
write("// Stan model for simple growth regression

data {
  int <lower = 1> N; // number of observations
  int <lower = 1> N_ant; // number of ant states
  int <lower = 1, upper = N_ant> ant[N]; // the list of ant species 
  vector[N] vol;	//size_t
  vector[N] y; // size_t1
}
parameters {
  vector[N_ant] beta0; //intercept, unique to ant sp
  vector[N_ant] beta1; //slope, unique to ant sp
  real<lower = 0> sigma;
}

transformed parameters{
  vector[N] mu; //linear predictor for the mean
  for(i in 1:N){
    mu[i] = beta0[ant[i]] + beta1[ant[i]] * vol[i];
  }
}

model {
  y ~ normal(mu, sigma); // likelihood
}",

"grow_ant_lm1.stan")

## Check that you wrote a file
stanc("grow_ant_lm1.stan")
## Save the file path
stanny <- "grow_ant_lm1.stan"
## Now we fit the model
fit_grow_ant <- stan(file = stanny, data = stan_data, warmup = 50, iter = 100, chains = 1, cores = 2, thin = 1)
fit_grow_ant
#class(fit)
posterior_grow_ant <- as.data.frame(fit_grow_ant)
lm_alpha_other <- summary(grow_model_ant_interact)$coeff[1]  # the intercept
lm_alpha_crem <- summary(grow_model_ant_interact)$coeff[3]
lm_alpha_liom <- summary(grow_model_ant_interact)$coeff[4]
lm_alpha_vacant <- summary(grow_model_ant_interact)$coeff[5]
lm_beta_other <- summary(grow_model_ant_interact)$coeff[2]  # the slope
lm_beta_crem <- summary(grow_model_ant_interact)$coeff[6]
lm_beta_liom <- summary(grow_model_ant_interact)$coeff[7]
lm_beta_vacant <- summary(grow_model_ant_interact)$coeff[8]
lm_sigma <- sigma(grow_model_ant_interact)  # the residual error

par(mfrow = c(2,4))
#Plot Intercepts
plot(density(posterior_grow_ant$`beta0[1]`), main = "Intercept Other")
abline(v = lm_alpha_other, col = 4, lty = 2)
plot(density(posterior_grow_ant$`beta0[2]`), main = "Intercept Crem")
abline(v = lm_alpha_crem, col = 4, lty = 2)
plot(density(posterior_grow_ant$`beta0[3]`), main = "Intercept Liom")
abline(v = lm_alpha_liom, col = 4, lty = 2)
plot(density(posterior_grow_ant$`beta0[4]`), main = "Intercept Vacant")
abline(v = lm_alpha_vacant, col = 4, lty = 2)
#Plot Slopes
plot(density(posterior_grow_ant$`beta1[1]`), main = "Intercept Other")
abline(v = lm_beta_other, col = 4, lty = 2)
plot(density(posterior_grow_ant$`beta1[2]`), main = "Intercept Crem")
abline(v = lm_beta_crem, col = 4, lty = 2)
plot(density(posterior_grow_ant$`beta1[3]`), main = "Intercept Liom")
abline(v = lm_beta_liom, col = 4, lty = 2)
plot(density(posterior_grow_ant$`beta1[4]`), main = "Intercept Vacant")
abline(v = lm_beta_vacant, col = 4, lty = 2)
#Sigma
plot(density(posterior_grow_ant$sigma), main = "Sigma")
abline(v = lm_sigma, col = 4, lty = 2)
```

####Survival

```{r survival}
vol = data$volume_t
y = data$Survival_t1
N = nrow(data)
N_ant = 4
ant = data$ant
stan_data <- list(N = N, ## number of observations
                  vol = vol, ## predictors volume
                  y = y, ## response survival next year
                  ant = ant,## predictors ants
                  N_ant = N_ant
                  ) 

write("// Stan model for simple ant survival regression

data {
  int <lower = 1> N; // number of observations
  int <lower = 1> N_ant; // number of ant states
  int <lower = 1, upper = N_ant> ant[N]; // the list of ant species 
  vector[N] vol;	//size_t
  int <lower = 0, upper = 1> y[N]; // survival in year t1
}

parameters {
  vector[N_ant] beta0; //intercept, unique to ant sp
  vector[N_ant] beta1; //slope, unique to ant sp
  real<lower = 0> sigma;
}

transformed parameters{
  vector[N] mu; //linear predictor for the mean
  for(i in 1:N){
    mu[i] = beta0[ant[i]] + beta1[ant[i]] * vol[i];
  }
}

model {
//Priors
 beta0 ~ normal(0,100);
 beta1 ~ normal(0,100);
 //Model
 y ~ bernoulli_logit(mu);
}
",

"surv_ant_lm1.stan")
## Check that you wrote a file
stanc("surv_ant_lm1.stan")
## Save the file path
stanny <- "surv_ant_lm1.stan"
## Now we fit the model
fit_surv_ant <- stan(file = stanny, data = stan_data, warmup = 500, iter = 1000, chains = 1, cores = 2, thin = 1)
fit_surv_ant

#class(fit)
posterior_surv_ant <- as.data.frame(fit_surv_ant)
print(colnames(posterior_surv_ant))
lm_alpha_other <- summary(surv_model_ant_interact)$coeff[1]  # the intercept
lm_alpha_crem <- summary(surv_model_ant_interact)$coeff[3]
lm_alpha_liom <- summary(surv_model_ant_interact)$coeff[4]
lm_alpha_vacant <- summary(surv_model_ant_interact)$coeff[5]
lm_beta_other <- summary(surv_model_ant_interact)$coeff[2]  # the slope
lm_beta_crem <- summary(surv_model_ant_interact)$coeff[6]
lm_beta_liom <- summary(surv_model_ant_interact)$coeff[7]
lm_beta_vacant <- summary(surv_model_ant_interact)$coeff[8]
lm_sigma <- sigma(surv_model_ant_interact)  # the residual error

par(mfrow = c(2,4))
#Plot Intercepts
plot(density(posterior_surv_ant$`beta0[1]`), main = "Intercept Other")
abline(v = lm_alpha_other, col = 4, lty = 2)
plot(density(posterior_surv_ant$`beta0[2]`), main = "Intercept Crem")
abline(v = lm_alpha_crem, col = 4, lty = 2)
plot(density(posterior_surv_ant$`beta0[3]`), main = "Intercept Liom")
abline(v = lm_alpha_liom, col = 4, lty = 2)
plot(density(posterior_surv_ant$`beta0[4]`), main = "Intercept Vacant")
abline(v = lm_alpha_vacant, col = 4, lty = 2)
#Plot Slopes
plot(density(posterior_surv_ant$`beta1[1]`), main = "Intercept Other")
abline(v = lm_beta_other, col = 4, lty = 2)
plot(density(posterior_surv_ant$`beta1[2]`), main = "Intercept Crem")
abline(v = lm_beta_crem, col = 4, lty = 2)
plot(density(posterior_surv_ant$`beta1[3]`), main = "Intercept Liom")
abline(v = lm_beta_liom, col = 4, lty = 2)
plot(density(posterior_surv_ant$`beta1[4]`), main = "Intercept Vacant")
abline(v = lm_beta_vacant, col = 4, lty = 2)
#Sigma
plot(density(posterior_surv_ant$sigma), main = "Sigma")
abline(v = lm_sigma, col = 4, lty = 2)
```

####Total Flowers

```{r total flowers}
y <- flower$TotFlowerbuds_t
vol = flower$volume_t
N = nrow(flower)
N_ant = 4
ant = flower$ant
stan_data <- list(N = N, ## number of observations
                  y = y, ## response survival next year
                  vol = vol,
                  N_ant = N_ant,
                  ant = ant
) 

write("// Stan model for simple total flowers regression

data {
 int <lower = 1> N; // number of observations
  int <lower = 1> N_ant; // number of ant states
  int <lower = 1, upper = N_ant> ant[N]; // the list of ant species 
  vector[N] vol;	//size_t
  int <lower = 0> y[N]; // survival in year t1
}

parameters {
  vector[N_ant] beta0; //intercept, unique to ant sp
  vector[N_ant] beta1; //slope, unique to ant sp
  real<lower = 0> sigma;
}

transformed parameters{
  vector[N] mu; //linear predictor for the mean
  for(i in 1:N){
    mu[i] = beta0[ant[i]] + beta1[ant[i]] * vol[i];
  }
}
model {
 // Model
 y ~ poisson(mu);
}
",

"flower_lm1.stan")
## Check that you wrote a file
stanc("flower_lm1.stan")
## Save the file path
stanny <- "flower_lm1.stan"
## Now we fit the model
fit_flow_ant <- stan(file = stanny, data = stan_data, warmup = 500, iter = 1000, chains = 1, cores = 2, thin = 1)
fit_flow_ant

posterior_flow_ant <- as.data.frame(fit_flow_ant)
print(colnames(posterior_flow_ant))

lm_alpha_other <- summary(flower_model_ant)$coeff[1]  # the intercept
lm_alpha_crem <- summary(flower_model_ant)$coeff[3]
lm_alpha_liom <- summary(flower_model_ant)$coeff[4]
lm_alpha_vacant <- summary(flower_model_ant)$coeff[5]
lm_beta_other <- summary(flower_model_ant)$coeff[2]  # the slope
lm_beta_crem <- summary(flower_model_ant)$coeff[6]
lm_beta_liom <- summary(flower_model_ant)$coeff[7]
lm_beta_vacant <- summary(flower_model_ant)$coeff[8]

par(mfrow = c(2,4))
#Plot Intercepts
plot(density(posterior_flow_ant$`beta0[1]`), main = "Intercept Other")
abline(v = lm_alpha_other, col = 4, lty = 2)
plot(density(posterior_flow_ant$`beta0[2]`), main = "Intercept Crem")
abline(v = lm_alpha_crem, col = 4, lty = 2)
plot(density(posterior_flow_ant$`beta0[3]`), main = "Intercept Liom")
abline(v = lm_alpha_liom, col = 4, lty = 2)
plot(density(posterior_flow_ant$`beta0[4]`), main = "Intercept Vacant")
abline(v = lm_alpha_vacant, col = 4, lty = 2)
#Plot Slopes
plot(density(posterior_flow_ant$`beta1[1]`), main = "Intercept Other")
abline(v = lm_beta_other, col = 4, lty = 2)
plot(density(posterior_flow_ant$`beta1[2]`), main = "Intercept Crem")
abline(v = lm_beta_crem, col = 4, lty = 2)
plot(density(posterior_flow_ant$`beta1[3]`), main = "Intercept Liom")
abline(v = lm_beta_liom, col = 4, lty = 2)
plot(density(posterior_flow_ant$`beta1[4]`), main = "Intercept Vacant")
abline(v = lm_beta_vacant, col = 4, lty = 2)
```


####Viability Model
```{r Viability model}
good <- flower$Goodbuds_t
abort <- flower$ABFlowerbuds_t
tot <- flower$TotFlowerbuds_t
vol = log(flower$volume_t)
N = nrow(flower)
N_ant = 4
ant = flower$ant
stan_data <- list(N = N, ## number of observations = trials
                  N_ant = N_ant,
                  ant = ant,
                  good = good, ## good buds = successes
                  abort = abort, ## aborted buds data
                  tot = tot, ## number of trials
                  vol = vol
) 

write("// Stan model for simple total flowers regression
data {
 int < lower = 1 > N; // Sample size
 int <lower = 0> good[N]; // Number of viable seeds
 int <lower = 1> N_ant; // number of ant states
 int <lower = 1, upper = N_ant> ant[N]; // the list of ant species 
 int<lower=0> tot[N]; // number of trials
 int<lower=0> abort[N];
 vector[N] vol;	//size_t
}
parameters {
  real <lower = 0, upper = 1> theta[N]; // probability of viability for each bud
  //
  real<lower=0,upper=1> v0;
  real<lower=0> a_v;
}
transformed parameters{
  real<lower=0,upper=1> predV[N]; // proportion viable for each plant?
  // Prediction for seed viability
  for(i in 1:N){
    predV[i] = v0 * pow(theta[ant[i]],good[i]) * (1-theta[ant[i]])^abort[i] ;
  }
}
model {
 // Priors
 v0  ~ beta(10,1);  // intercept viability model
  a_v ~ gamma(1,1);  // decay in viability with SR
  
  good ~ binomial(tot, predV);
}
", "viab_ant.stan")
## Check that you wrote a file
stanc("viab_ant.stan")
## Save the file path
stanny <- "viab_ant.stan"
## Now we fit the model
fit_viab <- stan(file = stanny, data = stan_data, warmup = 5, iter = 10, chains = 1, cores = 2, thin = 1)


posterior_viab_ant <- as.data.frame(fit_viab)

lm_alpha_other <- summary(viab_model_ant_interact)$coeff[1]  # the intercept
lm_alpha_crem <- summary(viab_model_ant_interact)$coeff[3]
lm_alpha_liom <- summary(viab_model_ant_interact)$coeff[4]
lm_alpha_vacant <- summary(viab_model_ant_interact)$coeff[5]
lm_beta_other <- summary(viab_model_ant_interact)$coeff[2]  # the slope
lm_beta_crem <- summary(viab_model_ant_interact)$coeff[6]
lm_beta_liom <- summary(viab_model_ant_interact)$coeff[7]
lm_beta_vacant <- summary(viab_model_ant_interact)$coeff[8]

par(mfrow = c(1,2))
#Plot Slopes
plot(density(posterior_viab_ant$`theta[1]`), main = "Viability Slope Distributions", col = "black", lwd = 2, xlim = c(-1,3), ylim =  c(0,2))
abline(v = lm_alpha_other, col = "black", lty = 2)
lines(density(posterior_viab_ant$`theta[2]`),  col = "red")
abline(v = lm_alpha_crem, col = "red", lty = 2)
lines(density(posterior_viab_ant$`theta[3]`),col = "blue", lwd = 2)
abline(v = lm_alpha_liom, col = "blue", lty = 2)
lines(density(posterior_viab_ant$`theta[4]`), col = "pink", lwd = 2)
abline(v = lm_alpha_vacant, col = "pink", lty = 2)
legend("topleft", legend = c("other","Crem.", "Liom.","Vac"), col = c("black","red","blue","pink"), lty = 1)
```

####Repro Model
```{r}
vol1 <- flower$volume_t1
y = flower$repro_state_t1
N = nrow(flower)
N_ant = 4
ant = flower$ant
stan_data <- list(N = N, ## number of observations
                  y = y, ## response survival next year
                  vol1 = vol1,
                  N_ant = N_ant,
                  ant = ant
)

write("// Stan model for simple total flowers regression

data {
  int <lower = 1> N; // number of observations
  int <lower = 1> N_ant; // number of ant states
  int <lower = 1, upper = N_ant> ant[N]; // the list of ant species 
  vector[N] vol1;	//size_t
  int <lower = 0, upper = 1> y[N]; // survival in year t1
}

parameters {
  vector[N_ant] beta0; //intercept, unique to ant sp
  vector[N_ant] beta1; //slope, unique to ant sp
  real<lower = 0> sigma;
}

transformed parameters{
  vector[N] mu; //linear predictor for the mean
  for(i in 1:N){
    mu[i] = beta0[ant[i]] + beta1[ant[i]] * vol1[i];
  }
}
model {
 // Priors
 beta0 ~ normal(0,100);
 beta1 ~ normal(0,100); 
 // Model
 y ~ bernoulli_logit(mu);
}
",

"repro_lm1.stan")

## Check that you wrote a file
stanc("repro_lm1.stan")
## Save the file path
stanny <- "repro_lm1.stan"
## Now we fit the model
fit_repro_ant <- stan(file = stanny, data = stan_data, warmup = 500, iter = 1000, chains = 1, cores = 2, thin = 1)
fit_repro_ant

posterior_repro_ant <- as.data.frame(fit_repro_ant)
print(colnames(posterior_repro_ant))

lm_alpha_other <- summary(model3)$coeff[1]  # the intercept
lm_alpha_crem <- summary(model3)$coeff[3]
lm_alpha_liom <- summary(model3)$coeff[4]
lm_alpha_vacant <- summary(model3)$coeff[5]
lm_beta_other <- summary(model3)$coeff[2]  # the slope
lm_beta_crem <- summary(model3)$coeff[6]
lm_beta_liom <- summary(model3)$coeff[7]
lm_beta_vacant <- summary(model3)$coeff[8]

par(mfrow = c(2,4))
#Plot Intercepts
plot(density(posterior_repro_ant$`beta0[1]`), main = "Intercept Other")
abline(v = lm_alpha_other, col = 4, lty = 2)
plot(density(posterior_repro_ant$`beta0[2]`), main = "Intercept Crem")
abline(v = lm_alpha_crem, col = 4, lty = 2)
plot(density(posterior_repro_ant$`beta0[3]`), main = "Intercept Liom")
abline(v = lm_alpha_liom, col = 4, lty = 2)
plot(density(posterior_repro_ant$`beta0[4]`), main = "Intercept Vacant")
abline(v = lm_alpha_vacant, col = 4, lty = 2)
#Plot Slopes
plot(density(posterior_repro_ant$`beta1[1]`), main = "Intercept Other")
abline(v = lm_beta_other, col = 4, lty = 2)
plot(density(posterior_repro_ant$`beta1[2]`), main = "Intercept Crem")
abline(v = lm_beta_crem, col = 4, lty = 2)
plot(density(posterior_repro_ant$`beta1[3]`), main = "Intercept Liom")
abline(v = lm_beta_liom, col = 4, lty = 2)
plot(density(posterior_repro_ant$`beta1[4]`), main = "Intercept Vacant")
abline(v = lm_beta_vacant, col = 4, lty = 2)
```

