---
title: "Cholla Ant Paper"
author: "Ali Campbell"
date: "4/7/2022"
output: pdf_document
bibliography: references.bib
document class: article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
opts_chunk$set(tidy.opts=list(width.cutoff=80),tidy=TRUE)
tinytex::install_tinytex()
```


#	Abstract
	Understanding interspecific mutualisms is challenging, because they are among the most widespread species interactions with dynamic consequences. One of the most important steps towards understanding lifelong demography impacts of mutualisms is quantifying the costs and benefits partners provide. In this study system Cilindropuntia imbracata (cholla cacti) attract ant partners, Crematogaster opuntiae (Crem.), Liometopum apiculatum (Liom.), as well as small populations of other ant species, by producing extrafloral nectar (EFN) and in return are defended from herbivores. The ant partners may be attracted to different qualities of EFN and differ in defensive effectiveness. If the cacti use significant energy to produce high quality nectar they may attract the most effective defender, but will have less energy for reproduction and growth. We ask “Which ant partner, or set of ant partners, is most effective and efficient for the cacti in this system?”. To determine this, we developed an Integral Projection Model (IPM) with Bayesian estimates, and used observational data from a 13 year study to parameterize the model. This lets us examine how interactions with different ant partners changes the fitness of the cacti population. This same framework is applicable to analyze other multispecies mutualisms to investigate partner contributions.
	
	Our results demonstrate the importance of evaluating mutualisms as dynamic systems. Our modeling found the vital rates of cholla vary depending on the partner present and that no partner is the “best” across the entire lifespan. The “best” partner appears to change across ontogeny. When these cholla cacti are young, they are unable to reproduce, instead all of their energy goes towards growth and EFN. We found that small cacti with the highest growth rates and survival rates are most commonly tended by Crem. ants. This indicates that Crem. is a very effective partner for small cacti. We found that larger cacti have the highest reproductive success when tended by Liom. ants, the most aggressive species observed interacting with these cacti. This aligns with the life state of reproduction, at which the cactus is most vulnerable to herbivory. Together these results show that the optimal partner will likely shift across the life stages of cholla cacti. There are a number of biodiversity hypotheses that may explain these phenomena, including complementarity and sampling effect. As we continue this project, we will investigate the grounds for these hypotheses.
	
# Introduction

# Bibliography





